import { ToolContent } from '../../registry/types';

export const aesEncryptDecrypt: ToolContent = {
  detailedDescription: `
### What is AES Encrypt Decrypt?
The **AES Encrypt Decrypt** tool provides military-grade encryption and decryption directly in your browser. Advanced Encryption Standard (AES) is a symmetric encryption algorithm established by the U.S. National Institute of Standards and Technology (NIST). It is the global standard for protecting sensitive data.

In line with KaruviLab's core philosophy, **all encryption happens locally on your device** using the Web Crypto API. Your passwords, raw keys, and plaintexts are never uploaded to any server. This guarantees absolute privacy and security for your sensitive information.

### Supported Modes & Key Derivation
- **AES-GCM (Galois/Counter Mode):** The modern, authenticated standard. It not only encrypts the data but also verifies its integrity, ensuring the ciphertext hasn't been tampered with. **(Highly Recommended)**
- **AES-CBC (Cipher Block Chaining):** A legacy block cipher mode that requires an exact Initialization Vector (IV). It does not natively provide integrity validation like GCM does, but remains widely used for compatibility.
- **PBKDF2 Key Derivation:** If you use a passphrase, we securely derive a high-entropy 256-bit AES key using PBKDF2 with a random salt and 100,000 iterations, providing strong resistance against brute-force attacks.

By keeping all cryptographic operations strictly within your browser, KaruviLab ensures that your text and files **never leave your device**.
`,
  howTo: [
    "**Step 1:** Select the operation mode: **Encrypt** or **Decrypt**.",
    "**Step 2:** Choose your AES Mode (**AES-GCM** is recommended for new data) and Key Size (usually 256-bit).",
    "**Step 3:** Enter a strong **Passphrase** (or provide a Raw Key if you know what you are doing).",
    "**Step 4:** Paste your sensitive text into the input field.",
    "**Step 5:** The tool will output a secure Base64 string containing your encrypted data (along with the necessary IV and Salt). To decrypt, paste this full string back into the Decrypt tab with the exact same password.",
  ],
  faq: [
    {
      question: "Is my data sent to a server?",
      answer: "No. All encryption and decryption operations are performed entirely within your browser using the native Web Crypto API. Your plaintext and passwords never leave your device.",
    },
    {
      question: "Which AES Mode should I choose?",
      answer: "Always use **AES-GCM** unless you specifically need backwards compatibility with an older system. GCM is an 'authenticated encryption' mode, meaning it detects if the encrypted data has been tampered with.",
    },
    {
      question: "I forgot my password. Can you recover my encrypted data?",
      answer: "No. We do not store your passwords, keys, or data. If you lose the password, the encrypted text is permanently inaccessible.",
    },
    {
      question: "Why does encrypting the same text with the same password produce a different output?",
      answer: "Because we generate a unique, cryptographically secure Salt and Initialization Vector (IV) for every single encryption operation. This is a critical security feature that prevents attackers from recognizing duplicate messages.",
    },
    {
      question: "What format is the output?",
      answer: "The output is encoded in Base64 so it can be easily copied and shared. It safely packages the Ciphertext, the Salt (if using a passphrase), and the IV into a single portable string.",
    }
  ],
  useCases: [
    "Secure Message Sharing: Encrypt a private message, send the ciphertext via a public channel (like email or chat), and share the password through a separate secure channel.",
    "Protect Sensitive Notes: Encrypt personal keys, seed phrases, or financial information before storing them in cloud notes.",
    "Developer Testing: Validate encryption implementations or debug ciphertext generated by backend systems (using Raw Key and Custom IV modes).",
    "Data Obfuscation: Temporarily hide information on screen from prying eyes."
  ],
  commonErrors: [
    {
      error: "Decryption Failed (OperationError)",
      fix: "This usually means you entered the wrong password, chose the wrong AES mode (e.g., trying to decrypt CBC data using GCM), or the encrypted string was truncated/modified."
    },
    {
      error: "Invalid IV Length",
      fix: "If you are using a Custom IV, ensure it is exactly 12 bytes for AES-GCM or 16 bytes for AES-CBC. A mismatched IV will fail to encrypt or decrypt."
    }
  ],
  alternatives: ["CyberChef", "OpenSSL Command Line", "GnuPG (GPG)"]
};
