import { ToolContent } from '../../registry/types';

export const csrGenerator: ToolContent = {
  detailedDescription: `
# KaruviLab Elite Learning Hub: CSR (Certificate Signing Request) Generator

Welcome to the definitive engineering guide to Certificate Signing Requests. This handbook explains the first critical step in securing a website with HTTPS.

---

## 1. Prerequisites: The Passport Analogy

Before you can get an SSL/TLS Certificate (the digital passport that gives your website a padlock icon), you have to formally apply for it. A **CSR** is your application.

**The Analogy:**
1. You go to a government office to get a passport. 
2. You hand them a form with your Name, City, and Country, along with your Photo. 
3. You sign the bottom of the form to prove you filled it out.
4. The government verifies your identity, stamps it, and hands you an official Passport.

In web security:
- The **Government** is the Certificate Authority (CA) like Let's Encrypt or DigiCert.
- The **Photo** is your Public Key.
- The **Signature** is generated by your Private Key.
- The **Form** is the CSR (Certificate Signing Request).
- The **Passport** is the final X.509 Certificate.

---

## 2. The PKI Ecosystem (Public Key Infrastructure)

\`\`\`mermaid
sequenceDiagram
    participant Web_Admin
    participant Browser_WebCrypto
    participant Certificate_Authority

    Web_Admin->>Browser_WebCrypto: Enter Domain, Org, City
    Note over Browser_WebCrypto: Generate RSA Key Pair (Public & Private)
    Note over Browser_WebCrypto: Package Public Key + Details into CSR
    Note over Browser_WebCrypto: Sign CSR with Private Key
    Browser_WebCrypto-->>Web_Admin: Returns CSR + Private Key
    Note over Web_Admin: Keeps Private Key completely secret!
    Web_Admin->>Certificate_Authority: Submits CSR file
    Note over Certificate_Authority: Validates signature and Domain Ownership
    Certificate_Authority-->>Web_Admin: Issues Signed X.509 Certificate
\`\`\`

---

## 3. Core Concepts & Structure

A CSR is formatted using a standard called **PKCS#10**. When you open a CSR file, it looks like random letters between \`-----BEGIN CERTIFICATE REQUEST-----\` and \`-----END CERTIFICATE REQUEST-----\`. This is Base64 (PEM) encoding.

If you decode it, a CSR contains exactly three parts:
1. **CertificationRequestInfo:** 
   - **Subject:** Your identity (Common Name/Domain, Organization, Country, etc.)
   - **Subject Public Key Info:** The actual Public Key bytes and algorithm (e.g., RSA 2048).
   - **Attributes:** Extra info like Subject Alternative Names (SANs) to secure multiple domains.
2. **Signature Algorithm:** Identifies the math used to sign it (e.g., \`sha256WithRSAEncryption\`).
3. **Signature Value:** The digital signature generated by your Private Key over the \`CertificationRequestInfo\`.

---

## 4. Threat Model & Security Review

| Threat | Defended By | Explanation |
|--------|-------------|-------------|
| **Man-in-the-Middle Forgery** | ✅ Signature | If a hacker intercepts your CSR and changes the domain to their own, the CA's signature verification will fail because the hacker doesn't have your Private Key to re-sign it. |
| **Private Key Theft** | ✅ Design | The Private Key is **never** included in the CSR. You only send the Public Key to the CA. |
| **Rogue CA Issuance** | ❌ No | A CSR doesn't stop a corrupt CA from issuing a fake certificate for your domain. (Mitigation: Certificate Transparency Logs and CAA DNS records). |

---

## 5. Browser Internals & Implementation

The native Web Crypto API (\`crypto.subtle\`) does not have a function to build PKCS#10 files. It only generates raw keys. 
To generate a CSR locally in KaruviLab:
1. We use \`crypto.subtle.generateKey()\` to generate the underlying RSA/ECC keys.
2. We use a pure JavaScript library (like \`pkijs\` or \`node-forge\`) to assemble the ASN.1 structure.
3. We pass the assembled ASN.1 bytes back to \`crypto.subtle.sign()\` to cryptographically sign the structure using the Private Key.
4. We Base64 encode the output into the final PEM format.

This entire pipeline runs offline in your RAM.

---

## 6. Production Workflows

### Scenario: Setting up NGINX with HTTPS
A DevOps engineer SSHs into a Linux server and runs:
\`openssl req -new -newkey rsa:2048 -nodes -keyout server.key -out server.csr\`
This generates the CSR. They paste the CSR text into their AWS or GoDaddy dashboard. GoDaddy verifies domain ownership via DNS, signs the CSR, and returns a \`.crt\` file. The engineer configures NGINX to use the \`.key\` and the \`.crt\` file, successfully enabling HTTPS on port 443.

---

## 7. Standards & References
- **RFC 2986:** PKCS #10: Certification Request Syntax Specification
- **RFC 7468:** Textual Encodings of PKIX, PKCS, and CMS Structures (PEM Format)

---

## 8. Interactive Quiz

**Beginner:**
1. Does a CSR contain your Private Key? *(Answer: No. Never. It only contains your Public Key and Identity details).*
2. Who do you send a CSR to? *(Answer: A Certificate Authority (CA) like Let's Encrypt, DigiCert, or your internal enterprise IT department).*

**Intermediate:**
3. Why does the CSR have a digital signature on it? *(Answer: To prove to the CA that the person requesting the certificate actually possesses the Private Key that matches the submitted Public Key).*

**Advanced:**
4. What is a SAN (Subject Alternative Name)? *(Answer: An attribute added to modern CSRs that allows a single certificate to secure multiple domains, e.g., \`example.com\` and \`www.example.com\`).*

---
*End of Elite Learning Hub Content.*
`,
  howTo: [
    "**Step 1:** Enter your Common Name (e.g., www.yourdomain.com).",
    "**Step 2:** Fill out the optional Organization, City, and Country fields.",
    "**Step 3:** Select your Key Size (2048-bit RSA is standard).",
    "**Step 4:** Click Generate. The tool will output both your new Private Key and your CSR.",
    "**Step 5:** Save your Private Key securely. Send ONLY the CSR to your Certificate Authority."
  ],
  faq: [
    {
      question: "Is my Private Key uploaded?",
      answer: "No. The key generation and CSR assembly happen locally in your browser. Your Private Key never leaves your machine."
    },
    {
      question: "What is a Common Name (CN)?",
      answer: "The Common Name is the Fully Qualified Domain Name (FQDN) you want to secure, like 'www.google.com' or 'api.stripe.com'."
    }
  ],
  useCases: [],
  examples: [],
  commonErrors: [],
  alternatives: ["RSA Key Generator", "X.509 Certificate Viewer"]
};
