import { ToolContent } from '../../registry/types';

export const emvTlvTree: ToolContent = {
  detailedDescription: `
# KaruviLab Elite Learning Hub: EMV & TLV Structures

Welcome to the engineering guide on EMV (Europay, Mastercard, Visa) specifications. This handbook decodes the sophisticated cryptography and data structures operating inside the microchip on your credit card.

---

## 1. Prerequisites: The Death of the Magnetic Stripe

For decades, credit cards used Magnetic Stripes (Magstripes). The stripe contained your Card Number (PAN) and Expiration Date in static plaintext. 
**The Problem:** A waitress could swipe your card through a "Skimmer" to copy the data, burn that data onto a blank hotel keycard, and perfectly clone your credit card.

**The Solution:** The EMV Microchip. A chip card is actually a tiny, highly secure computer without a battery. When inserted into a Point-of-Sale (POS) terminal, the terminal provides electricity to boot up the chip's OS (JavaCard). The terminal and the chip then engage in a complex cryptographic conversation. 
Because the chip executes internal math and generates a unique, one-time-use **Cryptogram** for every single transaction, **skimming a chip card is mathematically useless.** The cloned data will be rejected on the very next purchase.

---

## 2. Core Concepts: The TLV Data Structure

To facilitate this complex conversation, EMV uses a highly nested data format called **BER-TLV** (Basic Encoding Rules - Tag, Length, Value).

Every piece of data sent between the terminal and the chip consists of:
1. **Tag:** An identifier (e.g., \`9F02\`).
2. **Length:** How many bytes the value takes up (e.g., \`06\`).
3. **Value:** The actual data (e.g., \`000000005000\`).

**Why TLV?**
Unlike JSON (which is heavy and text-based) or ISO 8583 (which relies on strict positional bitmaps), TLV is highly flexible. If the terminal doesn't recognize a Tag, it reads the Length, skips exactly that many bytes, and safely moves to the next Tag. This allowed EMV to upgrade seamlessly over 20 years without breaking legacy terminals.

---

## 3. Architecture: Key EMV Tags

When you parse an EMV dump, you will see a massive tree of Hexadecimal tags. Here are the most critical:

- **Tag 9F02 (Amount Authorized):** The purchase amount the chip is agreeing to.
- **Tag 9F10 (Issuer Application Data):** Secret data the chip wants the bank's backend to see.
- **Tag 9F26 (Application Cryptogram):** The most important tag. This is an 8-byte cryptographic MAC generated by the chip. The terminal forwards this inside an ISO 8583 message (DE 55) to the bank. The bank recalculates it using a shared master key to prove the physical chip is genuinely present.
- **Tag 9F37 (Unpredictable Number):** A random number generated by the terminal to guarantee the transaction is fresh and cannot be replayed by a hacker.

---

## 4. Threat Model & Security Review

| Threat | Defended By | Explanation |
|--------|-------------|-------------|
| **Card Cloning / Skimming** | ✅ Dynamic Cryptogram | The chip generates a unique Tag 9F26 for every purchase. A thief who intercepts the data cannot reuse it because the next purchase requires a brand new cryptogram using the chip's internal unextractable Private Key. |
| **Offline PIN Forgery** | ✅ Secure Channel | Modern EMV executes Encrypted PIN Verification. The terminal encrypts the PIN using the chip's Public Key before sending it, preventing malware on the POS terminal from stealing the PIN. |
| **Relay Attacks** | ⚠️ Distance Bounding | Hackers can use two phones to "extend" the NFC range of a contactless card in your pocket to a terminal 50 miles away. Modern EMV mitigates this by strictly measuring the microsecond response time of the chip. |

---

## 5. Production Workflows

- **Apple Pay & Google Pay:** Your phone does not send a credit card number. It acts as a virtual EMV chip. It dynamically generates an EMV TLV payload, creates a unique Application Cryptogram using the Secure Enclave, and transmits it via NFC (Contactless EMV) to the terminal.
- **Payment Gateway Integration:** When a physical store upgrades their terminals, software engineers must write parsers to extract Tag \`9F26\` and \`9F02\` from the hardware, package them into an ISO 8583 Data Element 55, and route them to Stripe or Adyen.

---

## 6. Standards & References
- **EMV Book 3:** Application Specification.
- **ISO/IEC 7816-4:** Identification cards — Integrated circuit cards (defines the APDU commands and BER-TLV structures).

---

## 7. Interactive Quiz

**Beginner:**
1. Why is a chip more secure than a magnetic stripe? *(Answer: A magnetic stripe contains static data that is easily cloned. A chip generates a unique, one-time cryptographic code for every transaction).*

**Intermediate:**
2. What does TLV stand for? *(Answer: Tag, Length, Value. It is a highly efficient binary data structure).*
3. If an EMV terminal encounters a Tag it doesn't recognize, what does it do? *(Answer: It looks at the Length byte, skips exactly that many bytes, and continues parsing the rest of the message without crashing).*

**Advanced:**
4. What role does Tag 9F37 (Unpredictable Number) play in EMV security? *(Answer: It acts as a cryptographic nonce. By forcing the chip to include this random terminal-generated number in its Cryptogram calculation, it mathematically proves the transaction is happening live and prevents Replay Attacks).*

---

`,
  howTo: [
    "**Step 1:** Paste your raw Hexadecimal string containing the EMV TLV data (often found in ISO 8583 DE 55).",
    "**Step 2:** The engine will parse the BER-TLV structure and generate an interactive, nested tree view.",
    "**Step 3:** The parser automatically cross-references EMV Book 3 to label tags with their human-readable names (e.g., translating 9F02 to 'Amount Authorized')."
  ],
  faq: [
    {
      question: "Does parsing this data leak my card number?",
      answer: "It depends on the tags included. Tag 5A contains the Application Primary Account Number (PAN). You should never paste production EMV payloads containing Tag 5A into a public web browser."
    }
  ],
  useCases: [],
  examples: [],
  commonErrors: [],
  alternatives: ["ISO 8583 Message Parser"]
};
