import { ToolContent } from '../../registry/types';

export const samlDecoder: ToolContent = {
  detailedDescription: `
# KaruviLab Elite Learning Hub: SAML & Enterprise SSO

Welcome to the engineering guide to SAML (Security Assertion Markup Language). This handbook explains the XML-based behemoth that allows corporate employees to log into hundreds of different applications using just one password.

---

## 1. Prerequisites: The Enterprise Identity Nightmare

Imagine a corporation with 10,000 employees. Every employee uses Salesforce, Slack, Jira, and Zoom.
If every employee created a separate password for each app, they would have 40,000 passwords. When an employee is fired, the IT department would have to manually log into all 4 systems and delete the accounts before the rogue employee could steal data. 

**The Solution:** Single Sign-On (SSO) via **SAML**.
With SAML, the apps (Service Providers) do not handle passwords. When you try to log into Salesforce, it redirects you to a central corporate server (the Identity Provider, like Okta or Microsoft Entra). You log in once. The central server signs a cryptographically secure XML document saying *"This is John, let him in"*, and sends you back to Salesforce. 
When an employee is fired, IT clicks one button on the central server, and the employee is instantly locked out of all 4 apps.

---

## 2. Core Concepts: The SAML Triangle

SAML operates on a rigid trust relationship between three parties:

1. **The User (Principal):** The employee trying to log in.
2. **The Service Provider (SP):** The app providing the service (Salesforce, Slack).
3. **The Identity Provider (IdP):** The central authority verifying passwords (Okta, Active Directory).

### The SAML Assertion
The payload generated by the IdP is called an **Assertion**. It is a heavy, strictly formatted XML document.
- **Subject:** Who is this? (\`<NameID>\` e.g., john@corporate.com).
- **Conditions:** When is this valid? (\`<NotBefore>\` and \`<NotOnOrAfter>\`).
- **Attributes:** Extra data (e.g., \`<Attribute Name="Department"><AttributeValue>Sales</AttributeValue></Attribute>\`).
- **Signature:** An RSA-based XML digital signature proving the IdP generated this specific document.

---

## 3. Engineering Challenge: Encoding and Deflation

When the IdP generates the SAML Assertion, it doesn't send it directly to the SP via a backend API. Instead, it passes it *through the user's browser*. 

**The POST Binding:**
The IdP generates an HTML form containing a hidden input field named \`SAMLResponse\`. The value is the XML Assertion, Base64 encoded. JavaScript auto-submits the form to Salesforce.

**The Redirect Binding (The Deflate Trap):**
Sometimes, the Assertion is sent via a URL parameter (\`?SAMLRequest=...\`). Because URLs have length limits, standard Base64 encoding isn't enough. The XML is:
1. Compressed using the **Deflate (Zlib)** algorithm.
2. Base64 encoded.
3. URL encoded.
*(KaruviLab's decoder automatically handles this complex decompression pipeline).*

---

## 4. Threat Model & XML Signature Wrapping (XSW)

SAML is highly secure when configured correctly, but XML parsing is incredibly error-prone.

| Threat | Defended By | Explanation |
|--------|-------------|-------------|
| **Man-in-the-Middle** | ✅ XML Signatures | The entire Assertion is cryptographically signed using the IdP's private RSA key. If a hacker intercepts the SAMLResponse and changes the \`<NameID>\` from "hacker" to "CEO", the signature check fails. |
| **Replay Attacks** | ✅ Timestamps & IDs | The SP tracks the \`<AssertionID>\`. If a hacker records a valid SAML login and tries to submit it again tomorrow, the SP rejects it because the ID was already used, or the \`<NotOnOrAfter>\` timestamp has expired. |
| **XML Signature Wrapping (XSW)** | 🚨 SP Logic Bugs | **The most famous SAML hack.** The hacker injects a second, fake \`<Assertion>\` into the XML payload. Due to poorly written XML parsers, the SP verifies the signature on the *first* (valid) assertion, but actually logs the user in using the \`<NameID>\` from the *second* (fake, unsigned) assertion! |

---

## 5. Production Workflows vs OAuth/OIDC

Why does the enterprise still use SAML if OAuth and OpenID Connect (OIDC) are newer and use lightweight JSON?
- **Legacy Infrastructure:** SAML was released in 2005. Massive corporations and government agencies have spent decades building complex XML pipelines that cannot be easily replaced.
- **Attribute Richness:** SAML inherently supports passing massive, complex organizational data (clearances, departments, cost centers) directly in the payload.

---

## 6. Standards & References
- **OASIS SAML 2.0:** The official standard governing Assertions, Protocols, and Bindings.

---

## 7. Interactive Quiz

**Beginner:**
1. In the SAML flow, who actually verifies your password? *(Answer: The Identity Provider (IdP), such as Okta or Active Directory. The Service Provider (Salesforce) never sees your password).*

**Intermediate:**
2. Why is SAML considered a massive security upgrade for enterprise off-boarding? *(Answer: Because IT only has to disable the user's account in one central Identity Provider. The user instantly loses access to hundreds of connected Service Providers).*

**Advanced:**
3. What is an XML Signature Wrapping (XSW) attack? *(Answer: A catastrophic vulnerability where a hacker injects a fake XML assertion into the payload. If the Service Provider's XML parser is flawed, it verifies the signature of the legitimate assertion, but executes the login using the data from the fake assertion).*

---
*End of Elite Learning Hub Content.*
`,
  howTo: [
    "**Step 1:** Intercept the SAML login flow using your browser's Network tab.",
    "**Step 2:** Paste the raw encoded `SAMLResponse` or `SAMLRequest` payload.",
    "**Step 3:** The engine will automatically detect whether the payload is URL Encoded, Base64 Encoded, or Deflated (Zlib Compressed).",
    "**Step 4:** The tool decompresses and formats the raw XML, highlighting the <NameID>, Attributes, and Signature blocks."
  ],
  faq: [
    {
      question: "Why is the payload gibberish even after Base64 decoding?",
      answer: "SAML payloads passed in the URL (Redirect Binding) are usually compressed using the Deflate (Zlib) algorithm before being Base64 encoded to save space. Our tool automatically detects and decompresses this for you."
    }
  ],
  useCases: [],
  examples: [],
  commonErrors: [
    {
      error: "Deflate Decompression Failed",
      fix: "Ensure you are pasting the raw token and not a partially URL-decoded string. Some browser dev tools automatically URL-decode the string, breaking the Base64 sequence."
    }
  ],
  alternatives: ["OAuth Token Decoder", "XML Formatter"]
};
