/**
 * KaruviLab Mermaid Diagram Capability & Support Registry
 * Provides a centralized specification for all diagram types, support tiers, limits, and export capabilities.
 */

import { MermaidDiagramCapability, MermaidDiagramType, MermaidSupportLevel } from './types';

export const MERMAID_CAPABILITY_REGISTRY: Record<MermaidDiagramType, MermaidDiagramCapability> = {
  flowchart: {
    type: 'flowchart',
    displayName: 'Flowchart',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 200,
    maxRecommendedEdges: 300,
    description: 'Workflows, decision trees, and system logic flows with top-down or left-right layouts.',
  },
  sequenceDiagram: {
    type: 'sequenceDiagram',
    displayName: 'Sequence Diagram',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 50,
    maxRecommendedEdges: 150,
    description: 'Interaction timelines, message flows, and actor-to-service communication.',
  },
  classDiagram: {
    type: 'classDiagram',
    displayName: 'Class Diagram',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 60,
    maxRecommendedEdges: 120,
    description: 'Object-oriented class structures, interfaces, fields, and inheritance hierarchies.',
  },
  stateDiagram: {
    type: 'stateDiagram',
    displayName: 'State Machine',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 80,
    maxRecommendedEdges: 160,
    description: 'State transitions, lifecycle events, composite states, forks, and joins.',
  },
  erDiagram: {
    type: 'erDiagram',
    displayName: 'Entity-Relationship',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 50,
    maxRecommendedEdges: 100,
    description: 'Database schema modeling, relational entities, cardinalities, and keys.',
  },
  gantt: {
    type: 'gantt',
    displayName: 'Gantt Timeline',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 100,
    maxRecommendedEdges: 50,
    description: 'Project schedules, milestones, dependencies, critical paths, and resource timelines.',
  },
  gitGraph: {
    type: 'gitGraph',
    displayName: 'Git Graph',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 80,
    maxRecommendedEdges: 120,
    description: 'Version control branch histories, commit tracks, checkouts, and merges.',
  },
  mindmap: {
    type: 'mindmap',
    displayName: 'Mindmap',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 120,
    maxRecommendedEdges: 120,
    description: 'Hierarchical node trees for brainstorming, concept mapping, and knowledge vaults.',
  },
  timeline: {
    type: 'timeline',
    displayName: 'Roadmap Timeline',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 60,
    maxRecommendedEdges: 60,
    description: 'Historical timelines, chronological releases, and platform roadmaps.',
  },
  pie: {
    type: 'pie',
    displayName: 'Pie Chart',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 30,
    maxRecommendedEdges: 0,
    description: 'Proportional distributions, percentage breakdowns, and categorical metrics.',
  },
  quadrantChart: {
    type: 'quadrantChart',
    displayName: 'Quadrant Chart',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 40,
    maxRecommendedEdges: 0,
    description: '2x2 prioritization matrices, risk-reward grids, and value quadrant positioning.',
  },
  requirementDiagram: {
    type: 'requirementDiagram',
    displayName: 'Requirement Diagram',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 50,
    maxRecommendedEdges: 100,
    description: 'System specifications, test verifications, and requirement traceability matrices.',
  },
  journey: {
    type: 'journey',
    displayName: 'User Journey',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 40,
    maxRecommendedEdges: 40,
    description: 'User experience journeys, task steps, and sentiment tracking across persona roles.',
  },
  c4: {
    type: 'c4',
    displayName: 'C4 Architecture',
    supportLevel: 'stable',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 40,
    maxRecommendedEdges: 80,
    description: 'C4 model software architecture contexts, containers, components, and deployments.',
  },
  sankey: {
    type: 'sankey',
    displayName: 'Sankey Flow',
    supportLevel: 'experimental',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 50,
    maxRecommendedEdges: 100,
    description: 'Quantitative resource flows, capacity transfers, and cost distributions.',
  },
  xychart: {
    type: 'xychart',
    displayName: 'XY Bar / Line Chart',
    supportLevel: 'experimental',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 60,
    maxRecommendedEdges: 0,
    description: 'Continuous numerical series, bar graphs, and coordinate plotting.',
  },
  block: {
    type: 'block',
    displayName: 'Block Layout',
    supportLevel: 'experimental',
    mobileSupported: false,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 50,
    maxRecommendedEdges: 50,
    description: 'Grid-based hardware architecture blocks and sub-component enclosures.',
  },
  architecture: {
    type: 'architecture',
    displayName: 'Cloud Architecture',
    supportLevel: 'experimental',
    mobileSupported: false,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 40,
    maxRecommendedEdges: 80,
    description: 'Cloud infrastructure topologies, service clusters, and gateway connections.',
  },
  packet: {
    type: 'packet',
    displayName: 'Packet Header',
    supportLevel: 'experimental',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 32,
    maxRecommendedEdges: 0,
    description: 'Network packet structures, byte/bit segmentations, and binary field layouts.',
  },
  kanban: {
    type: 'kanban',
    displayName: 'Kanban Board',
    supportLevel: 'experimental',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 60,
    maxRecommendedEdges: 0,
    description: 'Workflow columns, task statuses, and agile sprint state boards.',
  },
  radar: {
    type: 'radar',
    displayName: 'Radar Chart',
    supportLevel: 'experimental',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 20,
    maxRecommendedEdges: 0,
    description: 'Multi-axis performance dimensions and skill comparison spider charts.',
  },
  treemap: {
    type: 'treemap',
    displayName: 'Treemap',
    supportLevel: 'experimental',
    mobileSupported: false,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 50,
    maxRecommendedEdges: 0,
    description: 'Nested hierarchical rectangles for file size and budget breakdowns.',
  },
  venn: {
    type: 'venn',
    displayName: 'Venn Diagram',
    supportLevel: 'experimental',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 10,
    maxRecommendedEdges: 0,
    description: 'Set theory intersections, overlapping group concepts, and logic relations.',
  },
  ishikawa: {
    type: 'ishikawa',
    displayName: 'Fishbone (Ishikawa)',
    supportLevel: 'experimental',
    mobileSupported: false,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 40,
    maxRecommendedEdges: 40,
    description: 'Cause-and-effect root cause failure analyses (Fishbone diagrams).',
  },
  wardley: {
    type: 'wardley',
    displayName: 'Wardley Map',
    supportLevel: 'experimental',
    mobileSupported: false,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 30,
    maxRecommendedEdges: 50,
    description: 'Strategic value chain positioning against market evolution stages.',
  },
  swimlane: {
    type: 'swimlane',
    displayName: 'Swimlane Process',
    supportLevel: 'experimental',
    mobileSupported: false,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 50,
    maxRecommendedEdges: 100,
    description: 'Cross-functional process flows separated across departmental lanes.',
  },
  treeview: {
    type: 'treeview',
    displayName: 'Tree View',
    supportLevel: 'experimental',
    mobileSupported: true,
    exportPdf: true,
    exportPng: true,
    exportSvg: true,
    maxRecommendedNodes: 80,
    maxRecommendedEdges: 0,
    description: 'File system directory trees, organizational hierarchy, and AST visualizations.',
  },
  unknown: {
    type: 'unknown',
    displayName: 'Custom / Unknown',
    supportLevel: 'unsupported',
    mobileSupported: false,
    exportPdf: false,
    exportPng: false,
    exportSvg: false,
    maxRecommendedNodes: 20,
    maxRecommendedEdges: 20,
    description: 'Unrecognized diagram syntax — raw source code is safely preserved without crashing.',
  },
};

export class MermaidRegistry {
  /**
   * Retrieve capability profile for a given diagram type.
   */
  public static getCapability(type: MermaidDiagramType): MermaidDiagramCapability {
    return MERMAID_CAPABILITY_REGISTRY[type] || MERMAID_CAPABILITY_REGISTRY.unknown;
  }

  /**
   * Check whether a diagram type has stable or experimental support.
   */
  public static isSupported(type: MermaidDiagramType): boolean {
    const cap = this.getCapability(type);
    return cap.supportLevel === 'stable' || cap.supportLevel === 'experimental';
  }

  /**
   * List all registered diagram capabilities.
   */
  public static getAllCapabilities(): MermaidDiagramCapability[] {
    return Object.values(MERMAID_CAPABILITY_REGISTRY);
  }

  /**
   * List all stable diagram capabilities.
   */
  public static getStableCapabilities(): MermaidDiagramCapability[] {
    return Object.values(MERMAID_CAPABILITY_REGISTRY).filter((c) => c.supportLevel === 'stable');
  }
}
