import { Metadata } from 'next';
import { CATEGORIES } from '@/src/tool-registry';
import { ToolShell } from '@/components/ui/ToolShell';
import { generateToolMetadata } from '@/src/lib/seo';
import { LearningHub, LearningSection } from '@/src/components/els/LearningHub';
import { QuizWidget } from '@/src/components/els/QuizWidget';
import TlvParserClientWrapper from './TlvParserClientWrapper';

const toolId = 'tlv-parser';
const cat = CATEGORIES.find(c => c.id === 'security');

export const metadata: Metadata = generateToolMetadata(toolId);

export default function Page() {
  return (
    <ToolShell
      title="EMV TLV Parser"
      description="Parse Tag-Length-Value (TLV / BER-TLV) hex data streams from EMV chip cards and payment terminals."
      category={cat}
      toolId={toolId}
    >
      <TlvParserClientWrapper />

      <LearningHub title="Understanding TLV & EMV">
        
        <LearningSection type="architecture" title="What is TLV?">
          <p>Tag-Length-Value (TLV) is a binary encoding scheme used extensively in telecommunications and EMV (chip-and-pin credit cards). Instead of using delimiters like commas or brackets, every piece of data is serialized into three distinct parts:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li><strong>Tag:</strong> A unique identifier (e.g., <code>5A</code> represents the PAN/Account Number).</li>
            <li><strong>Length:</strong> How many bytes of data follow.</li>
            <li><strong>Value:</strong> The actual data payload.</li>
          </ul>
        </LearningSection>
        
        <LearningSection type="api" title="The BER-TLV Standard">
          <p>EMV cards specifically use a subset of ASN.1 called <strong>BER-TLV</strong> (Basic Encoding Rules). BER-TLV supports complex nesting. A "Value" can actually contain another complete TLV structure inside it.</p>
          <p className="mt-2">To determine if a tag contains raw data or nested tags, parsers check the binary bits of the Tag byte. If the 6th bit (bit 5) is set to <code>1</code>, the tag is "Constructed" (nested). If it is <code>0</code>, the tag is "Primitive" (raw data).</p>
        </LearningSection>

        <LearningSection type="performance" title="Why not JSON?">
          <p>Why do credit card chips use TLV instead of JSON? <strong>Bandwidth and Memory.</strong></p>
          <p className="mt-2">Smart card chips have kilobytes of memory. JSON includes heavy text overhead (quotes, braces, literal string keys like <code>"accountNumber": "..."</code>). TLV strips all of this away. The identifier is just 1 or 2 bytes, the length is 1 byte, and the data is packed as raw binary. This allows a complete transaction cryptogram to fit into a tiny, ultra-fast payload.</p>
        </LearningSection>

        <LearningSection type="failures" title="Parsing the Length Field">
          <p>The most common bug when parsing EMV TLV is mishandling the Length byte. If the data is less than 128 bytes, the Length is a simple 1-byte integer.</p>
          <p className="mt-2">However, if the data is 128 bytes or larger, BER-TLV uses a multi-byte length. The first byte will have its highest bit set to <code>1</code> (e.g., <code>0x82</code>), indicating that the <em>next</em> 2 bytes contain the actual length. Naive parsers that assume the Length is always exactly 1 byte will catastrophically misread the rest of the stream.</p>
        </LearningSection>

        <LearningSection type="standards" title="Standards & References">
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>EMV 4.3 Specifications (Book 3):</strong> The definitive guide on how smart cards format application data using BER-TLV.</li>
            <li><strong>ISO/IEC 7816-4:</strong> Defines the APDU commands and the exact TLV structures used in smart card communication.</li>
            <li><strong>References:</strong> <a href="https://www.emvco.com/document-search/" target="_blank" rel="noreferrer" className="text-primary hover:underline">EMVCo Document Library</a></li>
          </ul>
        </LearningSection>

        <LearningSection type="general" title="Real-World Examples">
          <p>When you dip your chip card, the terminal reads TLV tags like:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li><strong>Tag 5A (Application Primary Account Number):</strong> The raw credit card number.</li>
            <li><strong>Tag 5F20 (Cardholder Name):</strong> Your name embossed on the card.</li>
            <li><strong>Tag 9F02 (Amount, Authorized):</strong> The exact amount of the transaction the chip is approving.</li>
            <li><strong>Tag 9F26 (Application Cryptogram):</strong> A unique, one-time cryptographic signature generated by the chip to prevent cloning.</li>
          </ul>
        </LearningSection>

        <LearningSection type="general" title="Check Your Knowledge" fullWidth>
          <QuizWidget 
            questions={[
              {
                question: "Why do EMV smart cards use TLV encoding instead of JSON?",
                options: [
                  "TLV is heavily encrypted, while JSON is plain text.",
                  "JSON cannot represent numbers.",
                  "TLV is extremely space-efficient, which is critical for smart card chips with very limited memory.",
                  "TLV is a newer standard than JSON."
                ],
                correctIndex: 2,
                explanation: "Smart cards operate under severe hardware constraints. TLV minimizes overhead (no quotes, no long string keys) to fit complex data into a few bytes."
              },
              {
                question: "In BER-TLV, if a parser reads a Tag and determines it is 'Constructed', what does that mean?",
                options: [
                  "The Value portion contains raw text data.",
                  "The Value portion contains nested TLV structures.",
                  "The data is encrypted.",
                  "The data was corrupted during transmission."
                ],
                correctIndex: 1,
                explanation: "A 'Constructed' tag means the value isn't primitive data; it is a container holding one or more child TLV objects, requiring the parser to recurse."
              }
            ]}
          />
        </LearningSection>
      </LearningHub>
    </ToolShell>
  );
}
