import { Metadata } from 'next';
import { CATEGORIES } from '@/src/tool-registry';
import { ToolShell } from '@/components/ui/ToolShell';
import { generateToolMetadata } from '@/src/lib/seo';
import { LearningHub, LearningSection } from '@/src/components/els/LearningHub';
import { QuizWidget } from '@/src/components/els/QuizWidget';

import CompressPdfClientWrapper from './CompressPdfClientWrapper';

const toolId = 'compress-pdf';
const cat = CATEGORIES.find(c => c.id === 'pdf');

export const metadata: Metadata = generateToolMetadata(toolId);

export default function Page() {
  return (
    <ToolShell 
      title="Compress PDF"
      description="Reduce PDF file size by re-encoding with pdf-lib's object stream compression."
      category={cat}
      toolId={toolId}
    >
      <CompressPdfClientWrapper />

      <LearningHub title="Understanding PDF Compression">
        
        <LearningSection type="architecture" title="More Than Just Images">
          <p>Unlike images (JPEG/PNG) which are grids of pixels, a PDF is a complex relational database of objects (fonts, vectors, text, images, and metadata). Compressing a PDF requires parsing this database and rewriting it more efficiently.</p>
        </LearningSection>
        
        <LearningSection type="api" title="Object Streams (PDF 1.5+)">
          <p>Older PDFs store every object individually, which creates a lot of overhead. This tool upgrades the PDF structure to use <strong>Object Streams</strong>.</p>
          <p className="mt-2">This feature groups multiple objects together and compresses the entire group using the <code>FlateDecode</code> (zlib) algorithm, significantly reducing the file size of vector and text-heavy documents.</p>
        </LearningSection>

        <LearningSection type="performance" title="Metadata & Orphan Removal">
          <p>PDFs often contain invisible "orphan" objects—fonts that were embedded but are no longer used, or massive XML metadata payloads from creation tools like Adobe Illustrator.</p>
          <p className="mt-2">The "High" compression setting aggressively traverses the document tree to strip out Document Information dictionaries and unreachable objects.</p>
        </LearningSection>

        <LearningSection type="security" title="The Scanned Document Trap">
          <p>This tool performs <strong>structural compression</strong>, not image degradation. If your PDF is just a scanned document (a giant JPEG wrapped in a PDF envelope), the structure is already minimal.</p>
          <p className="mt-2">To compress a scanned PDF further, you would need to lower the resolution or quality of the embedded image itself, which requires heavy raster image-processing algorithms that this structural tool does not attempt.</p>
        </LearningSection>

        <LearningSection type="general" title="Check Your Knowledge" fullWidth>
          <QuizWidget 
            questions={[
              {
                question: "What is an 'Object Stream' in the context of a PDF file?",
                options: [
                  "A streaming protocol for downloading PDFs over the network.",
                  "A method of grouping multiple PDF objects together and compressing them as a single block.",
                  "A video file embedded inside the PDF.",
                  "A DRM mechanism to prevent unauthorized printing."
                ],
                correctIndex: 1,
                explanation: "Introduced in PDF 1.5, Object Streams allow the FlateDecode algorithm to compress many objects at once, which is much more efficient than compressing them individually."
              },
              {
                question: "Why might a 10MB PDF generated by a scanner not shrink significantly when using this tool?",
                options: [
                  "Because scanners use a proprietary encryption format.",
                  "Because the PDF is already using Object Streams.",
                  "Because the file is essentially a single large JPEG wrapped in a PDF, and this tool optimizes structure rather than degrading image quality.",
                  "Because browser security prevents modifying scanned documents."
                ],
                correctIndex: 2,
                explanation: "Structural compression is highly effective on text and vector PDFs with many objects, but cannot shrink a single embedded image without actively reducing its resolution."
              }
            ]}
          />
        </LearningSection>
      </LearningHub>
    </ToolShell>
  );
}
