export interface CommandEntry {
  id?: string;
  cmd: string;
  desc: string;
  category: 'Git' | 'Linux' | 'Windows' | 'macOS' | 'SSH/SFTP' | 'Permissions' | 'OpenSSL' | 'Editors' | 'Network' | 'Node/npm' | 'Docker' | 'Kubernetes' | 'Python' | 'Hashing';
  linux?: string;
  mac?: string;
  windows?: string;
  details?: string;
  syntax?: string;
  example?: string;
  warning?: string;
}

export const COMMANDS_DATA: CommandEntry[] = [
  // ── EDITORS (NANO & VI/VIM) ──
  {
    id: 'nano-open',
    category: 'Editors',
    cmd: 'nano <file>',
    desc: 'Open or create a file in Nano text editor',
    linux: 'nano <file>',
    mac: 'nano <file>',
    windows: 'notepad <file> (or Install Nano via WSL/Scoop)',
    details: 'Nano is a user-friendly terminal text editor available on most Unix-like operating systems. Shortcuts use Ctrl or Alt key combinations.',
    syntax: 'nano [options] <filename>',
    example: 'nano ~/.bashrc',
  },
  {
    id: 'nano-save',
    category: 'Editors',
    cmd: 'Ctrl + O',
    desc: 'Nano: Save / Write Out changes to file',
    linux: 'Ctrl + O (Press Enter to confirm filename)',
    mac: 'Control + O (Press Return to confirm filename)',
    windows: 'Ctrl + O (inside Nano window)',
    details: 'Saves current buffer to disk without exiting Nano. You will be prompted to confirm or rename the file path.',
    example: 'Press Ctrl+O -> Press Enter',
  },
  {
    id: 'nano-exit',
    category: 'Editors',
    cmd: 'Ctrl + X',
    desc: 'Nano: Exit editor (prompts to save if modified)',
    linux: 'Ctrl + X',
    mac: 'Control + X',
    windows: 'Ctrl + X (inside Nano window)',
    details: 'Exits Nano. If you have unsaved changes, Nano asks (Y/N) whether to write modified buffer before quitting.',
    example: 'Press Ctrl+X -> Press Y -> Press Enter to save and quit',
  },
  {
    id: 'nano-cut',
    category: 'Editors',
    cmd: 'Ctrl + K',
    desc: 'Nano: Cut current line to clipboard (Kill text)',
    linux: 'Ctrl + K',
    mac: 'Control + K',
    windows: 'Ctrl + K (inside Nano window)',
    details: 'Deletes (cuts) the line at the cursor position and stores it in Nano\'s internal paste buffer.',
    example: 'Place cursor on target line -> Ctrl+K',
  },
  {
    id: 'nano-paste',
    category: 'Editors',
    cmd: 'Ctrl + U',
    desc: 'Nano: Uncut / Paste line from clipboard',
    linux: 'Ctrl + U',
    mac: 'Control + U',
    windows: 'Ctrl + U (inside Nano window)',
    details: 'Pastes (uncuts) the text stored in Nano\'s cut buffer at the current cursor position.',
    example: 'Ctrl+K (cut) -> Move cursor -> Ctrl+U (paste)',
  },
  {
    id: 'nano-search',
    category: 'Editors',
    cmd: 'Ctrl + W',
    desc: 'Nano: Search for text string (Where Is)',
    linux: 'Ctrl + W',
    mac: 'Control + W',
    windows: 'Ctrl + W (inside Nano window)',
    details: 'Opens a search prompt at the bottom of the screen. Pressing Alt+W will search for the next occurrence.',
    example: 'Ctrl+W -> Type "export PATH" -> Press Enter',
  },
  {
    id: 'nano-replace',
    category: 'Editors',
    cmd: 'Ctrl + \\',
    desc: 'Nano: Search and Replace text',
    linux: 'Ctrl + \\ (or Alt + R)',
    mac: 'Control + \\ (or Option + R)',
    windows: 'Ctrl + \\ (inside Nano window)',
    details: 'Prompts for search text, then replacement text, and asks to replace occurrences individually or all at once.',
    example: 'Ctrl+\\ -> Search: "http" -> Replace: "https" -> Press A (All)',
  },
  {
    id: 'nano-goto-line',
    category: 'Editors',
    cmd: 'Ctrl + _',
    desc: 'Nano: Jump to specific line and column number',
    linux: 'Ctrl + _ (or Alt + G)',
    mac: 'Control + _ (or Option + G)',
    windows: 'Ctrl + _ (inside Nano window)',
    details: 'Prompts for a line number and column position to jump the cursor directly.',
    example: 'Ctrl+_ -> Type "142,5" -> Jump to line 142 column 5',
  },
  {
    id: 'nano-mark-text',
    category: 'Editors',
    cmd: 'Alt + A',
    desc: 'Nano: Set mark to select a block of text',
    linux: 'Alt + A (or Esc + A)',
    mac: 'Option + A (or Esc + A)',
    windows: 'Alt + A (inside Nano window)',
    details: 'Starts text selection from current cursor position. Use arrow keys to highlight text, then Ctrl+K to cut or Alt+6 to copy.',
    example: 'Alt+A -> Arrow right/down to highlight -> Alt+6 to copy',
  },
  {
    id: 'nano-copy-marked',
    category: 'Editors',
    cmd: 'Alt + 6',
    desc: 'Nano: Copy selected marked text',
    linux: 'Alt + 6 (or Esc + 6)',
    mac: 'Option + 6 (or Esc + 6)',
    windows: 'Alt + 6 (inside Nano window)',
    details: 'Copies highlighted text marked with Alt+A into Nano\'s paste buffer without deleting it.',
    example: 'Alt+A -> Highlight text -> Alt+6 (Copy) -> Move cursor -> Ctrl+U (Paste)',
  },

  // Vi / Vim
  { category: 'Editors', cmd: 'vi <file>', desc: 'Open file in Vi/Vim editor', linux: 'vi <file>', mac: 'vim <file>', windows: 'vim <file>', details: 'Standard modal text editor in Unix environments.' },
  { category: 'Editors', cmd: 'i', desc: 'Vi: Enter Insert mode (Edit text)', details: 'Allows typing text into the file.' },
  { category: 'Editors', cmd: 'Esc', desc: 'Vi: Return to Command mode', details: 'Exits Insert mode and returns to Command mode.' },
  { category: 'Editors', cmd: ':wq', desc: 'Vi: Save and Quit', details: 'Writes changes to disk and exits Vi.' },
  { category: 'Editors', cmd: ':q!', desc: 'Vi: Quit without saving', details: 'Discards all unsaved changes and quits.' },
  { category: 'Editors', cmd: 'dd', desc: 'Vi: Delete current line', details: 'Deletes line under cursor and puts it in buffer.' },
  { category: 'Editors', cmd: 'yy', desc: 'Vi: Yank (Copy) current line', details: 'Copies current line into Vim register.' },
  { category: 'Editors', cmd: 'p', desc: 'Vi: Paste after cursor', details: 'Pastes text from register after cursor.' },

  // ── SSH & SFTP ──
  {
    id: 'ssh-connect',
    category: 'SSH/SFTP',
    cmd: 'ssh <user>@<host>',
    desc: 'Connect to a remote server over SSH',
    linux: 'ssh user@hostname',
    mac: 'ssh user@hostname',
    windows: 'ssh user@hostname (PowerShell / OpenSSH)',
    details: 'Establishes an encrypted SSH shell session with remote machine on default port 22.',
    example: 'ssh root@192.168.1.50 -p 22',
  },
  {
    id: 'ssh-keygen-ed25519',
    category: 'SSH/SFTP',
    cmd: 'ssh-keygen -t ed25519 -C "email@domain.com"',
    desc: 'Generate a high-security Ed25519 SSH key pair',
    linux: 'ssh-keygen -t ed25519 -C "admin@example.com"',
    mac: 'ssh-keygen -t ed25519 -C "admin@example.com"',
    windows: 'ssh-keygen -t ed25519 -C "admin@example.com"',
    details: 'Ed25519 is faster, safer, and shorter than traditional 2048/4096-bit RSA keys. Public key is saved to ~/.ssh/id_ed25519.pub.',
    syntax: 'ssh-keygen -t <algorithm> -b <bits> -C "<comment>"',
    example: 'ssh-keygen -t ed25519 -C "dev@karuvilab.com"',
  },
  {
    id: 'ssh-copy-id',
    category: 'SSH/SFTP',
    cmd: 'ssh-copy-id -i ~/.ssh/id_ed25519.pub user@host',
    desc: 'Copy public key to remote server for passwordless login',
    linux: 'ssh-copy-id user@host',
    mac: 'cat ~/.ssh/id_ed25519.pub | ssh user@host "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"',
    windows: 'type $env:USERPROFILE\\.ssh\\id_ed25519.pub | ssh user@host "cat >> ~/.ssh/authorized_keys"',
    details: 'Appends your public key to target user\'s ~/.ssh/authorized_keys file with correct 600 permissions.',
    example: 'ssh-copy-id -i ~/.ssh/id_ed25519.pub admin@10.0.0.1',
  },
  {
    id: 'ssh-manual-copy',
    category: 'SSH/SFTP',
    cmd: 'cat ~/.ssh/id_ed25519.pub',
    desc: 'Display public key content for manual copy & paste',
    linux: 'cat ~/.ssh/id_ed25519.pub',
    mac: 'pbcopy < ~/.ssh/id_ed25519.pub',
    windows: 'Get-Content $env:USERPROFILE\\.ssh\\id_ed25519.pub | Set-Clipboard',
    details: 'Prints public key text so you can add it to GitHub, GitLab, AWS EC2, or remote authorized_keys.',
    example: 'cat ~/.ssh/id_ed25519.pub',
  },
  {
    id: 'ssh-fix-permissions',
    category: 'SSH/SFTP',
    cmd: 'chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys ~/.ssh/id_*',
    desc: 'Fix SSH directory and key permissions (required for login)',
    linux: 'chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_ed25519',
    mac: 'chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_ed25519',
    windows: 'icacls %USERPROFILE%\\.ssh\\id_ed25519 /inheritance:r /grant:r "%USERNAME%":"(F)"',
    details: 'SSH clients reject private keys if file permissions are too open. SSH folder must be 700 and private keys/authorized_keys must be 600.',
    warning: 'If permissions are not 600, SSH connection will fail with "WARNING: UNPROTECTED PRIVATE KEY FILE!"',
  },
  {
    id: 'ssh-tunnel-local',
    category: 'SSH/SFTP',
    cmd: 'ssh -L 8080:localhost:3000 user@remote-server',
    desc: 'Setup local SSH port forwarding tunnel',
    linux: 'ssh -L 8080:localhost:3000 user@remote-server',
    mac: 'ssh -L 8080:localhost:3000 user@remote-server',
    windows: 'ssh -L 8080:localhost:3000 user@remote-server',
    details: 'Forwards local port 8080 to remote port 3000 through encrypted SSH connection. Access remote web servers safely via http://localhost:8080.',
    example: 'ssh -N -f -L 5432:localhost:5432 user@db-server.com',
  },
  {
    id: 'ssh-fingerprint',
    category: 'SSH/SFTP',
    cmd: 'ssh-keygen -l -f ~/.ssh/id_ed25519.pub',
    desc: 'Inspect SHA256 fingerprint of an SSH key',
    linux: 'ssh-keygen -l -f ~/.ssh/id_ed25519.pub',
    mac: 'ssh-keygen -l -f ~/.ssh/id_ed25519.pub',
    windows: 'ssh-keygen -l -f $env:USERPROFILE\\.ssh\\id_ed25519.pub',
    details: 'Outputs key length, SHA256 fingerprint hash, and key comment for identity validation.',
    example: 'ssh-keygen -lf ~/.ssh/known_hosts',
  },

  // ── PERMISSIONS & FILE SECURITY ──
  {
    id: 'chmod-basic',
    category: 'Permissions',
    cmd: 'chmod 755 <path>',
    desc: 'Set standard executable permissions (rwxr-xr-x)',
    linux: 'chmod 755 script.sh',
    mac: 'chmod 755 script.sh',
    windows: 'icacls script.ps1 /grant Users:(RX)',
    details: 'Read/Write/Execute for Owner (7 = rwx), Read/Execute for Group (5 = r-x) and Others (5 = r-x). Common for scripts & folders.',
    syntax: 'chmod <octal_mode> <file_or_directory>',
    example: 'chmod 755 deploy.sh',
  },
  {
    id: 'chmod-private',
    category: 'Permissions',
    cmd: 'chmod 600 <private_file>',
    desc: 'Restrict access to owner read/write only (rw-------)',
    linux: 'chmod 600 config.json',
    mac: 'chmod 600 config.json',
    windows: 'icacls config.json /inheritance:r /grant:r %USERNAME%:F',
    details: 'Required for API tokens, SSL private keys, and SSH keys. Prevents other system users from viewing or modifying file.',
    example: 'chmod 600 ~/.env',
  },
  {
    id: 'chmod-recursive',
    category: 'Permissions',
    cmd: 'chmod -R 644 <files> && find <dir> -type d -exec chmod 755 {} +',
    desc: 'Set standard web server permissions recursively',
    linux: 'find /var/www -type f -exec chmod 644 {} + && find /var/www -type d -exec chmod 755 {} +',
    mac: 'find . -type f -exec chmod 644 {} + && find . -type d -exec chmod 755 {} +',
    windows: 'icacls C:\\inetpub\\wwwroot /grant Users:(R)',
    details: 'Applies 644 (rw-r--r--) to files and 755 (rwxr-xr-x) to directories across web directory trees.',
  },
  {
    id: 'chown-basic',
    category: 'Permissions',
    cmd: 'chown -R user:group /path/to/dir',
    desc: 'Change ownership of files and directories recursively',
    linux: 'sudo chown -R www-data:www-data /var/www/html',
    mac: 'sudo chown -R $USER:staff ./project',
    windows: 'takeown /f "C:\\Folder" /r /d y',
    details: 'Assigns user and group ownership for target directory tree.',
    example: 'sudo chown -R nginx:nginx /usr/share/nginx/html',
  },

  // ── OPENSSL & SECURITY ──
  {
    id: 'openssl-genrsa',
    category: 'OpenSSL',
    cmd: 'openssl genrsa -out private.key 4096',
    desc: 'Generate a 4096-bit RSA Private Key',
    linux: 'openssl genrsa -out private.key 4096',
    mac: 'openssl genrsa -out private.key 4096',
    windows: 'openssl genrsa -out private.key 4096',
    details: 'Creates an unencrypted 4096-bit RSA private key file encoded in PEM format.',
    example: 'openssl genrsa -out domain.key 4096',
  },
  {
    id: 'openssl-pubkey',
    category: 'OpenSSL',
    cmd: 'openssl rsa -in private.key -pubout -out public.key',
    desc: 'Extract RSA Public Key from Private Key',
    linux: 'openssl rsa -in private.key -pubout -out public.key',
    mac: 'openssl rsa -in private.key -pubout -out public.key',
    windows: 'openssl rsa -in private.key -pubout -out public.key',
    details: 'Extracts public key components from private key into PEM format.',
    example: 'openssl rsa -in private.key -pubout -out public.pem',
  },
  {
    id: 'openssl-csr',
    category: 'OpenSSL',
    cmd: 'openssl req -new -key private.key -out domain.csr',
    desc: 'Generate a Certificate Signing Request (CSR)',
    linux: 'openssl req -new -key private.key -out domain.csr',
    mac: 'openssl req -new -key private.key -out domain.csr',
    windows: 'openssl req -new -key private.key -out domain.csr',
    details: 'Prompts for Subject Info (CN, OU, O, C) and generates CSR file to submit to CA.',
    example: 'openssl req -new -key key.pem -out request.csr -subj "/CN=example.com"',
  },
  {
    id: 'openssl-selfsign',
    category: 'OpenSSL',
    cmd: 'openssl req -x509 -new -nodes -key private.key -sha256 -days 365 -out cert.pem',
    desc: 'Generate a self-signed X.509 SSL certificate for dev',
    linux: 'openssl req -x509 -new -nodes -key key.pem -sha256 -days 365 -out cert.pem',
    mac: 'openssl req -x509 -new -nodes -key key.pem -sha256 -days 365 -out cert.pem',
    windows: 'openssl req -x509 -new -nodes -key key.pem -sha256 -days 365 -out cert.pem',
    details: 'Generates a 1-year self-signed SSL/TLS certificate without needing an external Certificate Authority.',
    example: 'openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt',
  },
  {
    id: 'openssl-view-cert',
    category: 'OpenSSL',
    cmd: 'openssl x509 -text -noout -in cert.pem',
    desc: 'Inspect full details of an X.509 certificate',
    linux: 'openssl x509 -text -noout -in cert.pem',
    mac: 'openssl x509 -text -noout -in cert.pem',
    windows: 'openssl x509 -text -noout -in cert.pem',
    details: 'Displays Issuer, Subject, Validity dates, SANs (Subject Alternative Names), and serial numbers.',
    example: 'openssl x509 -enddate -noout -in cert.pem',
  },
  {
    id: 'openssl-sclient',
    category: 'OpenSSL',
    cmd: 'openssl s_client -connect hostname.com:443 -showcerts',
    desc: 'Debug TLS handshake and inspect live server SSL certificate chain',
    linux: 'openssl s_client -connect example.com:443 -showcerts',
    mac: 'openssl s_client -connect example.com:443 -showcerts',
    windows: 'openssl s_client -connect example.com:443 -showcerts',
    details: 'Establishes TLS handshake with server, displaying full certificate chain and cipher negotiation results.',
    example: 'echo Q | openssl s_client -connect google.com:443 -servername google.com',
  },
  {
    id: 'openssl-pkcs12',
    category: 'OpenSSL',
    cmd: 'openssl pkcs12 -export -out cert.pfx -inkey key.pem -in cert.pem',
    desc: 'Convert PEM certificate and private key to PFX / PKCS12',
    linux: 'openssl pkcs12 -export -out bundle.pfx -inkey private.key -in cert.crt',
    mac: 'openssl pkcs12 -export -out bundle.pfx -inkey private.key -in cert.crt',
    windows: 'openssl pkcs12 -export -out bundle.pfx -inkey private.key -in cert.crt',
    details: 'Bundles certificate and key into password-protected PKCS#12 (.pfx/.p12) format required by Windows IIS / Azure.',
  },

  // ── LINUX / UNIX ──
  {
    id: 'linux-ls',
    category: 'Linux',
    cmd: 'ls -la',
    desc: 'List all files with details, permissions, and hidden files',
    linux: 'ls -la',
    mac: 'ls -laG',
    windows: 'dir /ah (CMD) or Get-ChildItem -Hidden (PowerShell)',
    details: 'Shows permissions, owner, group, file size, modification date, and hidden dot-files.',
  },
  {
    id: 'linux-grep',
    category: 'Linux',
    cmd: 'grep -rnw "/path/" -e "pattern"',
    desc: 'Search for text pattern recursively with line numbers',
    linux: 'grep -rnw "." -e "API_KEY"',
    mac: 'grep -rnw "." -e "API_KEY"',
    windows: 'findstr /s /n /i "API_KEY" *.* (CMD) or Select-String (PowerShell)',
    details: 'r = recursive, n = line numbers, w = match whole word.',
  },
  {
    id: 'linux-systemctl',
    category: 'Linux',
    cmd: 'sudo systemctl restart <service>',
    desc: 'Restart system service daemon (systemd)',
    linux: 'sudo systemctl restart nginx',
    mac: 'sudo launchctl kickstart -k system/<service>',
    windows: 'Restart-Service -Name <service> (PowerShell)',
    details: 'Controls background services on systemd Linux distributions (Ubuntu, Debian, CentOS, RHEL).',
  },
  {
    id: 'linux-lsof',
    category: 'Linux',
    cmd: 'lsof -i :<port>',
    desc: 'Find process ID (PID) listening on a specific network port',
    linux: 'lsof -i :8080',
    mac: 'lsof -i :8080',
    windows: 'netstat -ano | findstr :8080 (CMD)',
    details: 'Displays command, PID, and user associated with target port.',
    example: 'kill -9 $(lsof -t -i:8080)',
  },

  // ── WINDOWS ──
  {
    id: 'win-netstat',
    category: 'Windows',
    cmd: 'netstat -ano | findstr :<port>',
    desc: 'Find active listening ports and process IDs on Windows',
    linux: 'netstat -tulnp (or ss -tulnp)',
    mac: 'netstat -anv | grep LISTEN',
    windows: 'netstat -ano | findstr :3000',
    details: 'Displays active TCP/UDP connections with process IDs (PID).',
  },
  {
    id: 'win-sfc',
    category: 'Windows',
    cmd: 'sfc /scannow',
    desc: 'Scan and repair corrupted Windows system files',
    windows: 'sfc /scannow (Run as Administrator)',
    details: 'System File Checker scans integrity of all protected system files and replaces corrupted versions.',
  },

  // ── GIT ──
  { id: 'git-init', category: 'Git', cmd: 'git init', desc: 'Initialize a new local Git repository', linux: 'git init', mac: 'git init', windows: 'git init' },
  { id: 'git-clone', category: 'Git', cmd: 'git clone <url>', desc: 'Clone remote repository from GitHub / GitLab', linux: 'git clone <url>', mac: 'git clone <url>', windows: 'git clone <url>' },
  { id: 'git-stash', category: 'Git', cmd: 'git stash push -m "message"', desc: 'Stash uncommitted changes with message', linux: 'git stash', mac: 'git stash', windows: 'git stash' },
  { id: 'git-log', category: 'Git', cmd: 'git log --oneline --graph --all', desc: 'View graphical commit tree history', linux: 'git log --oneline --graph', mac: 'git log --oneline --graph', windows: 'git log --oneline --graph' },

  // ── NETWORK & CURL ──
  {
    id: 'curl-post-json',
    category: 'Network',
    cmd: 'curl -X POST <url> -H "Content-Type: application/json" -d \'{"key":"value"}\'',
    desc: 'Send HTTP POST request with JSON payload',
    linux: 'curl -X POST https://api.com/v1 -H "Content-Type: application/json" -d \'{"name":"test"}\'',
    mac: 'curl -X POST https://api.com/v1 -H "Content-Type: application/json" -d \'{"name":"test"}\'',
    windows: 'Invoke-RestMethod -Uri https://api.com/v1 -Method POST -Body \'{"name":"test"}\' -ContentType "application/json"',
    details: 'Performs HTTP POST request with custom headers and body data.',
  },
  {
    id: 'curl-headers',
    category: 'Network',
    cmd: 'curl -I <url>',
    desc: 'Fetch HTTP headers only (HEAD request)',
    linux: 'curl -I https://karuvilab.com',
    mac: 'curl -I https://karuvilab.com',
    windows: 'curl.exe -I https://karuvilab.com',
    details: 'Returns HTTP response status code, server header, cache control, and security headers.',
  },

  // ── DOCKER ──
  { id: 'docker-ps', category: 'Docker', cmd: 'docker ps -a', desc: 'List all running and stopped containers', linux: 'docker ps -a', mac: 'docker ps -a', windows: 'docker ps -a' },
  { id: 'docker-exec', category: 'Docker', cmd: 'docker exec -it <container_id> /bin/bash', desc: 'Open interactive bash terminal inside container', linux: 'docker exec -it <id> sh', mac: 'docker exec -it <id> sh', windows: 'docker exec -it <id> sh' },
  { id: 'docker-prune', category: 'Docker', cmd: 'docker system prune -a --volumes', desc: 'Clean up unused containers, images, networks, and volumes', warning: 'Deletes all stopped containers and dangling images!' },

  // ── NODE / NPM ──
  { id: 'npm-init', category: 'Node/npm', cmd: 'npm init -y', desc: 'Initialize package.json with defaults' },
  { id: 'npm-install', category: 'Node/npm', cmd: 'npm install <pkg>', desc: 'Install production npm package' },
  { id: 'npm-dev', category: 'Node/npm', cmd: 'npm i -D <pkg>', desc: 'Install dev dependency package' },
  { id: 'npx-exec', category: 'Node/npm', cmd: 'npx <package>@latest', desc: 'Execute package binary without permanent installation' },
];

export const COMMAND_CATEGORIES = [
  'All',
  'Editors',
  'SSH/SFTP',
  'Permissions',
  'OpenSSL',
  'Git',
  'Linux',
  'Windows',
  'Network',
  'Docker',
  'Node/npm',
] as const;
