import { Metadata } from 'next';
import { CATEGORIES } from '@/src/tool-registry';
import { ToolShell } from '@/components/ui/ToolShell';
import { generateToolMetadata } from '@/src/lib/seo';
import { LearningHub, LearningSection } from '@/src/components/els/LearningHub';
import { QuizWidget } from '@/src/components/els/QuizWidget';

import MarkdownEditorWrapper from '@/src/features/markdown/MarkdownEditorWrapper';

const toolId = 'markdown';
const cat = CATEGORIES.find(c => c.id === 'utilities');

export const metadata: Metadata = generateToolMetadata(toolId);

export default function Page() {
  return (
    <ToolShell 
      title="Markdown Editor"
      description="Write, preview and export Markdown with support for Mermaid diagrams and syntax highlighting."
      category={cat}
      toolId={toolId}
      workspaceSize="wide"
    >
      <MarkdownEditorWrapper />

      <LearningHub title="Understanding Markdown and XSS Security">
        
        <LearningSection type="architecture" title="Markdown and HTML">
          <p>Markdown is a lightweight markup language created by John Gruber in 2004. Its core philosophy is that formatted text should be readable as plain text, without looking like it's been marked up with tags.</p>
          <p className="mt-2">A parser reads the text line by line. When it sees syntax like <code># Hello</code>, it replaces it with the corresponding HTML <code>&lt;h1&gt;Hello&lt;/h1&gt;</code>.</p>
        </LearningSection>
        
        <LearningSection type="security" title="The XSS Vulnerability">
          <p>By design, the Markdown specification allows authors to use raw HTML directly within the document. If you type <code>&lt;button&gt;Click&lt;/button&gt;</code>, the parser leaves it alone and it renders as a functional button.</p>
          <p className="mt-2">This is incredibly dangerous in modern web applications (like comments sections). If an attacker writes a Markdown post containing <code>&lt;script&gt;stealCookies()&lt;/script&gt;</code>, the naive parser will blindly output that script into the browser's DOM, executing malicious code instantly.</p>
        </LearningSection>

        <LearningSection type="api" title="The Solution: DOMPurify">
          <p>To prevent Cross-Site Scripting (XSS), KaruviLab forces all rendered HTML through a library called <strong>DOMPurify</strong> before it ever touches your screen.</p>
          <p className="mt-2">The purifier analyzes the parsed HTML tree, strips out all dangerous elements (<code>&lt;script&gt;</code>, <code>&lt;iframe&gt;</code>) and malicious event attributes (<code>onclick=</code>), while preserving safe display tags (headings, bold, images). This guarantees you can safely preview any unknown Markdown file without risking device compromise.</p>
        </LearningSection>

        <LearningSection type="general" title="Check Your Knowledge" fullWidth>
          <QuizWidget 
            questions={[
              {
                question: "Why is rendering raw Markdown generated by users considered a security risk?",
                options: [
                  "Because Markdown files are too large and cause Denial of Service.",
                  "Because the Markdown spec allows raw HTML, meaning a malicious user can inject <script> tags to execute code (XSS).",
                  "Because Markdown contains tracking pixels.",
                  "Because it bypasses the browser's SSL certificate."
                ],
                correctIndex: 1,
                explanation: "Markdown's allowance for raw HTML makes it a prime vector for Cross-Site Scripting (XSS) attacks if the output isn't aggressively sanitized."
              },
              {
                question: "What is the industry-standard way to fix the Markdown XSS vulnerability?",
                options: [
                  "Pass the final HTML output through a sanitizer like DOMPurify before injecting it into the page.",
                  "Disable JavaScript entirely.",
                  "Encrypt the Markdown file.",
                  "Only allow users to type in lowercase letters."
                ],
                correctIndex: 0,
                explanation: "Sanitizers like DOMPurify parse the HTML string and remove any executable vectors (scripts, iframes, onload attributes) while keeping the visual formatting intact."
              }
            ]}
          />
        </LearningSection>
      </LearningHub>
    </ToolShell>
  );
}
