import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | KaruviLab",
  description: "Read the Terms of Service for KaruviLab. Understand permitted usage, intellectual property, and user responsibilities when using our browser-native tools.",
};

export default function TermsOfService() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-16 space-y-8">
      <h1 className="text-4xl font-black tracking-tight text-text">Terms of Service</h1>
      <p className="text-text-4 font-bold">Effective Date: May 30, 2026</p>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">1. Acceptance of Terms</h2>
        <p>
          By accessing and using KaruviLab (https://karuvilab.com), you accept and agree to be bound by the terms and provision of this agreement. 
          If you do not agree to abide by these terms, please do not use our services.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">2. Description of Service & Permitted Usage</h2>
        <p>
          KaruviLab provides a suite of browser-based utility tools, including but not limited to calculators, PDF manipulators, image converters, and developer utilities. 
          The Service is provided for personal, educational, and professional use. You may use the output generated by our tools for commercial purposes, 
          provided you do not violate any third-party copyrights or these Terms.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">3. User Responsibilities</h2>
        <p>When using KaruviLab, you agree to the following responsibilities:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Lawful Use:</strong> You will not use the tools for any illegal or unauthorized purpose.</li>
          <li><strong>Data Ownership:</strong> Because files are processed locally on your device, you are solely responsible for ensuring you have the right to process, modify, or convert any documents, images, or data you load into the browser.</li>
          <li><strong>No Abuse:</strong> You agree not to reverse-engineer, scrape, or perform automated bulk attacks (DDoS) against our hosting infrastructure or APIs.</li>
        </ul>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">4. Prohibited Activities</h2>
        <p>Users are strictly prohibited from:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Attempting to bypass security measures or sandboxing applied to the HTML/Developer tools.</li>
          <li>Using the platform to generate or process malicious code, viruses, or illegal materials.</li>
          <li>Framing or mirroring the website without explicit written permission from KaruviLab.</li>
        </ul>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">5. Intellectual Property</h2>
        <p>
          The layout, design, branding, logo, code, and content of the KaruviLab website are the exclusive property of KaruviLab. 
          You may not copy, reproduce, or distribute the website's source code or visual design without permission. 
          However, you retain all intellectual property rights to the files, code, and data you process using our tools.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">6. Service Availability & Modifications</h2>
        <p>
          KaruviLab strives to ensure high availability, leveraging offline-capable Progressive Web App (PWA) technologies. 
          However, we do not guarantee uninterrupted access to the site. We reserve the right to modify, suspend, or discontinue 
          any tool or feature at any time, with or without notice.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">7. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, KaruviLab, its founders, and its affiliates shall not be liable for any indirect, 
          incidental, special, consequential, or punitive damages, or any loss of profits, revenues, or data, resulting from:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Your use or inability to use the tools.</li>
          <li>Any inaccuracies or errors in the calculations or outputs generated by the tools.</li>
          <li>Data loss resulting from clearing your browser cache or malfunctioning local storage.</li>
        </ul>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">8. Termination Rights</h2>
        <p>
          We reserve the right to block IP addresses or terminate access to our web services for users who violate these Terms of Service, 
          engage in abusive behavior, or attempt to compromise the integrity of the platform.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">9. Governing Law</h2>
        <p>
          These Terms shall be governed and construed in accordance with standard international digital commerce laws, 
          without regard to its conflict of law provisions. Any disputes arising from the use of the platform shall be resolved in 
          the applicable jurisdiction of the platform's operating business entity.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">10. Contact Details</h2>
        <p>For questions or concerns regarding these Terms of Service, please reach out to us at:</p>
        <p><strong>Email:</strong> <a href="mailto:support@karuvilab.com" className="text-blue hover:underline">support@karuvilab.com</a></p>
      </section>
    </div>
  );
}