import { Metadata } from 'next';
import { CATEGORIES } from '@/src/tool-registry';
import { ToolShell } from '@/components/ui/ToolShell';
import { ToolInfoSection } from '@/components/ui/ToolInfoSection';
import { generateToolMetadata } from '@/src/lib/seo';

import XmlFormatterWrapper from './XmlFormatterWrapper';

const toolId = 'xml-formatter';
const cat = CATEGORIES.find(c => c.id === 'developer');

export const metadata: Metadata = generateToolMetadata(toolId);

export default function Page() {
  return (
    <ToolShell 
      title="XML Formatter"
      description="Format, minify, and validate XML."
      category={cat}
      toolId={toolId}
    >
      <XmlFormatterWrapper />

      <div className="mt-16 space-y-6 max-w-4xl mx-auto w-full">
        <ToolInfoSection
          id="learn-xml"
          title="How it Works: XML vs JSON"
          preview="Learn why XML is still heavily used in enterprise systems and how it differs from JSON."
        >
          <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none">
            <p>
              XML (eXtensible Markup Language) was designed to store and transport data. Unlike JSON, which was born from JavaScript and designed for web APIs, XML was designed to be both machine-readable and highly structured using tags (like HTML).
            </p>
            <h3>Attributes vs Elements</h3>
            <p>
              One of the main differences from JSON is that XML allows data to be stored in two ways: <strong>Elements</strong> (tags) and <strong>Attributes</strong>. For example:
            </p>
            <pre><code>
&lt;user id="123"&gt;
  &lt;name&gt;Alice&lt;/name&gt;
&lt;/user&gt;
            </code></pre>
            <p>
              In this example, <code>id</code> is an attribute, while <code>name</code> is a child element. JSON lacks a native concept of attributes.
            </p>
            <h3>Why format it?</h3>
            <p>
              XML generated by systems (like SOAP APIs, RSS feeds, or sitemaps) is often "minified"—meaning all line breaks and spaces are removed to save bandwidth. This makes it a single, massive line of text that is completely unreadable to humans. Formatting it parses the XML tree and adds consistent indentation (pretty-printing).
            </p>
          </div>
        </ToolInfoSection>
      </div>
    </ToolShell>
  );
}
