import { Metadata } from 'next';
import { CATEGORIES } from '@/src/tool-registry';
import { ToolShell } from '@/components/ui/ToolShell';
import { generateToolMetadata } from '@/src/lib/seo';
import { LearningHub, LearningSection } from '@/src/components/els/LearningHub';
import { QuizWidget } from '@/src/components/els/QuizWidget';

import XmlFormatterWrapper from './XmlFormatterWrapper';

const toolId = 'xml-formatter';
const cat = CATEGORIES.find(c => c.id === 'developer');

export const metadata: Metadata = generateToolMetadata(toolId);

export default function Page() {
  return (
    <ToolShell 
      title="XML Formatter"
      description="Format, minify, and validate XML."
      category={cat}
      toolId={toolId}
    >
      <XmlFormatterWrapper />

      <LearningHub title="Understanding XML and Document Structures">
        
        <LearningSection type="architecture" title="XML vs JSON">
          <p>XML (eXtensible Markup Language) was designed in the late 1990s to store and transport data. Unlike JSON, which was born from JavaScript arrays and objects, XML was designed to be highly structured using nested tags (identical in syntax to HTML).</p>
          <p className="mt-2">While JSON is heavily favored for modern Web APIs, XML remains the backbone of massive enterprise systems, banking protocols (like ISO 20022), SOAP APIs, and document storage formats (like Microsoft Office <code>.docx</code> files).</p>
        </LearningSection>
        
        <LearningSection type="api" title="Attributes vs Elements">
          <p>One of the main structural differences from JSON is that XML allows data to be stored in two distinct ways: <strong>Elements</strong> (tags) and <strong>Attributes</strong>.</p>
          <pre className="my-2 bg-kv-surface-2 p-3 rounded-md overflow-x-auto text-sm text-kv-text font-mono border border-kv-border">
{`<user id="123">
  <name>Alice</name>
</user>`}
          </pre>
          <p>In this example, <code>id</code> is an Attribute embedded directly into the opening tag, while <code>name</code> is a child Element containing a text node. This distinction allows for complex metadata organization that JSON cannot natively replicate.</p>
        </LearningSection>

        <LearningSection type="performance" title="Parsing Complexity">
          <p>XML is significantly heavier to parse than JSON. To format it, a parser must construct a full DOM (Document Object Model) tree in memory.</p>
          <p className="mt-2">XML generated by automated systems is often "minified"—meaning all line breaks and spaces are aggressively removed to save network bandwidth. Formatting it requires walking the DOM tree and re-inserting consistent indentation (pretty-printing) so human engineers can debug it.</p>
        </LearningSection>

        <LearningSection type="general" title="Check Your Knowledge" fullWidth>
          <QuizWidget 
            questions={[
              {
                question: "Which of the following is a key structural feature of XML that JSON lacks?",
                options: [
                  "The ability to store numbers.",
                  "The ability to nest arrays infinitely.",
                  "The ability to store data as Attributes inside the opening tag of an element.",
                  "The ability to use boolean values."
                ],
                correctIndex: 2,
                explanation: "XML allows data to be stored as Elements (child tags) or Attributes (metadata on the tag). JSON only has Key-Value pairs."
              },
              {
                question: "Why do automated systems usually 'minify' XML before sending it over the network?",
                options: [
                  "To encrypt the data.",
                  "To remove all whitespace and line breaks, significantly reducing the file size and saving network bandwidth.",
                  "To prevent parsers from reading it.",
                  "To convert it into binary code."
                ],
                correctIndex: 1,
                explanation: "Whitespace has no meaning to a machine parser. Removing it minimizes the payload size, making API responses faster."
              }
            ]}
          />
        </LearningSection>
      </LearningHub>
    </ToolShell>
  );
}
