import { ToolEntry } from '../types';

export const BREAK_TIME_TOOLS: ToolEntry[] = [
  {
    id: 'tic-tac-toe',
    name: 'Tic-Tac-Toe',
    desc: 'Classic 2-player Tic-Tac-Toe right in your browser. No downloads, no sign-in.',
    href: 'break-time-tools/tic-tac-toe/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-09',
    keywords: ['tic tac toe', 'game', 'fun', 'brain break', 'two player', 'noughts and crosses'],
    input: null,
    output: null,
    related: ['memory-match', 'game-2048'],
    subCategory: 'Games',
    requiresNetwork: false,
    difficulty: 'beginner',
    priority: 0.6,
    schemaType: 'WebApplication',
  },
  {
    id: 'game-2048',
    name: '2048',
    desc: 'Slide and merge tiles to reach 2048. Addictive puzzle game — fully offline.',
    href: 'break-time-tools/game-2048/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-09',
    keywords: ['2048', 'puzzle', 'game', 'sliding tiles', 'merge', 'brain training', 'fun'],
    input: null,
    output: null,
    related: ['tic-tac-toe', 'memory-match'],
    subCategory: 'Games',
    requiresNetwork: false,
    difficulty: 'intermediate',
    priority: 0.6,
    schemaType: 'WebApplication',
  },
  {
    id: 'memory-match',
    name: 'Memory Match',
    desc: 'Flip cards and match pairs. A classic memory-training game with best-score tracking.',
    href: 'break-time-tools/memory-match/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-09',
    keywords: ['memory match', 'card flip', 'pairs', 'concentration', 'brain training', 'game', 'fun'],
    input: null,
    output: null,
    related: ['tic-tac-toe', 'game-2048'],
    subCategory: 'Brain Training',
    requiresNetwork: false,
    difficulty: 'beginner',
    priority: 0.6,
    schemaType: 'WebApplication',
  },
  {
    id: 'reaction-time',
    name: 'Reaction Time Test',
    desc: 'Test your reflexes and measure your reaction speed in milliseconds.',
    href: 'break-time-tools/reaction-time/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-10',
    keywords: ['reaction time', 'reflexes', 'speed', 'test', 'brain game', 'cognitive'],
    input: null,
    output: null,
    related: ['color-match', 'tic-tac-toe'],
    subCategory: 'Skill Tests',
    requiresNetwork: false,
    difficulty: 'beginner',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
  {
    id: 'color-match',
    name: 'Color Match',
    desc: 'Pick the exact color swatch under time pressure to test your visual accuracy.',
    href: 'break-time-tools/color-match/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-10',
    keywords: ['color match', 'color test', 'swatch', 'visual accuracy', 'reflex', 'game'],
    input: null,
    output: null,
    related: ['reaction-time', 'memory-match'],
    subCategory: 'Skill Tests',
    requiresNetwork: false,
    difficulty: 'intermediate',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
];
