import { ToolEntry } from '../types';

export const BREAK_TIME_TOOLS: ToolEntry[] = [
  {
    id: 'tic-tac-toe',
    name: 'Tic-Tac-Toe',
    desc: 'Classic 2-player Tic-Tac-Toe right in your browser. Play vs a friend or challenge the AI with multiple difficulty levels.',
    href: 'break-time-tools/tic-tac-toe/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-09',
    keywords: ['tic tac toe', 'game', 'fun', 'brain break', 'two player', 'noughts and crosses', 'ai'],
    input: null,
    output: null,
    related: ['memory-match', 'game-2048', 'snake-game'],
    subCategory: 'Games',
    requiresNetwork: false,
    difficulty: 'beginner',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
  {
    id: 'game-2048',
    name: '2048',
    desc: 'Slide and merge tiles to reach 2048. Fully offline with move history and undo support.',
    href: 'break-time-tools/game-2048/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-09',
    keywords: ['2048', 'puzzle', 'game', 'sliding tiles', 'merge', 'brain training', 'fun', 'undo'],
    input: null,
    output: null,
    related: ['tic-tac-toe', 'memory-match', 'sudoku'],
    subCategory: 'Games',
    requiresNetwork: false,
    difficulty: 'intermediate',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
  {
    id: 'snake-game',
    name: 'Snake Game',
    desc: 'Play the classic retro Snake game. Eat food, grow longer, and set new high scores entirely in your browser.',
    href: 'break-time-tools/snake-game/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-11',
    keywords: ['snake', 'arcade', 'retro', 'classic game', 'brain break', 'fun', 'offline'],
    input: null,
    output: null,
    related: ['game-2048', 'reaction-time', 'tic-tac-toe'],
    subCategory: 'Games',
    requiresNetwork: false,
    difficulty: 'intermediate',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
  {
    id: 'memory-match',
    name: 'Memory Match',
    desc: 'Flip cards and match pairs. A classic memory-training game with multiple grid sizes and best-score tracking.',
    href: 'break-time-tools/memory-match/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-09',
    keywords: ['memory match', 'card flip', 'pairs', 'concentration', 'brain training', 'game', 'fun'],
    input: null,
    output: null,
    related: ['tic-tac-toe', 'game-2048', 'word-guess'],
    subCategory: 'Brain Training',
    requiresNetwork: false,
    difficulty: 'beginner',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
  {
    id: 'reaction-time',
    name: 'Reaction Time Test',
    desc: 'Test your reflexes and measure your reaction speed in milliseconds.',
    href: 'break-time-tools/reaction-time/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-10',
    keywords: ['reaction time', 'reflexes', 'speed', 'test', 'brain game', 'cognitive'],
    input: null,
    output: null,
    related: ['color-match', 'tic-tac-toe', 'snake-game'],
    subCategory: 'Skill Tests',
    requiresNetwork: false,
    difficulty: 'beginner',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
  {
    id: 'color-match',
    name: 'Color Match',
    desc: 'Pick the exact color swatch under time pressure to test your visual accuracy.',
    href: 'break-time-tools/color-match/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-10',
    keywords: ['color match', 'color test', 'swatch', 'visual accuracy', 'reflex', 'game'],
    input: null,
    output: null,
    related: ['reaction-time', 'memory-match', 'word-guess'],
    subCategory: 'Skill Tests',
    requiresNetwork: false,
    difficulty: 'intermediate',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    desc: 'Classic 9x9 Sudoku logical number placement puzzle with multiple difficulty modes, hints, and local best times.',
    href: 'break-time-tools/sudoku/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-11',
    keywords: ['sudoku', 'number puzzle', 'logic game', 'brain training', 'puzzle', 'offline'],
    input: null,
    output: null,
    related: ['game-2048', 'memory-match', 'word-guess'],
    subCategory: 'Puzzles',
    requiresNetwork: false,
    difficulty: 'intermediate',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    desc: 'Classic Minesweeper puzzle. Clear the board without clicking on hidden mines. Multiple difficulties and mobile friendly controls.',
    href: 'break-time-tools/minesweeper/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-11',
    keywords: ['minesweeper', 'mines', 'logic game', 'classic game', 'brain break', 'offline'],
    input: null,
    output: null,
    related: ['sudoku', 'game-2048', 'memory-match'],
    subCategory: 'Puzzles',
    requiresNetwork: false,
    difficulty: 'intermediate',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
  {
    id: 'word-guess',
    name: 'Word Guess',
    desc: 'A word guessing puzzle game. Find the secret 5-letter word in 6 tries using visual feedback.',
    href: 'break-time-tools/word-guess/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-11',
    keywords: ['word guess', 'wordle', 'word game', 'puzzle', 'vocabulary', 'brain training', 'spelling', 'offline'],
    input: null,
    output: null,
    related: ['memory-match', 'color-match', 'tic-tac-toe'],
    subCategory: 'Word Games',
    requiresNetwork: false,
    difficulty: 'intermediate',
    priority: 0.8,
    schemaType: 'WebApplication',
  },
];
