// Auto-generated.
import { ToolEntry } from '../types';
export const CALCULATORS_TOOLS: ToolEntry[] = [
  {
    "id": "age-calculator",
    "name": "Age Calculator",
    "desc": "Calculate age in years, months, and days",
    "href": "calculators/age-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "age",
      "birthday",
      "years"
    ],
    "input": null,
    "output": null,
    "related": [
      "date-calculator",
      "time-calculator"
    ],
    "subCategory": "Date & Time",
    "requiresNetwork": false
  },
  {
    "id": "bmi-calculator",
    "name": "BMI Calculator",
    "desc": "Calculate your Body Mass Index with visual healthy range indicator. Supports metric and imperial units with Indian body type context.",
    "href": "calculators/bmi-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "bmi calculator",
      "body mass index",
      "health",
      "weight",
      "fitness",
      "healthy weight",
      "bmi india"
    ],
    "input": null,
    "output": null,
    "related": [
      "emi-calculator",
      "age-calculator",
      "sip-calculator"
    ],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "cagr-calculator",
    "name": "CAGR Calculator",
    "desc": "Compound Annual Growth Rate",
    "href": "calculators/cagr-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "cagr",
      "growth",
      "return",
      "annualized"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "compound-interest",
    "name": "Compound Interest Calculator",
    "desc": "Calculate compounded growth on your investment.",
    "href": "calculators/compound-interest/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "compound interest",
      "interest calculator",
      "investment growth",
      "savings calculator"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "currency-converter",
    "name": "Currency Converter",
    "desc": "Convert between world currencies",
    "href": "calculators/currency-converter/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "currency",
      "exchange",
      "forex",
      "usd",
      "eur",
      "inr"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Math & Units",
    "requiresNetwork": true
  },
  {
    "id": "data-calculator",
    "name": "Data Calculator",
    "desc": "Units, transfer time, cost, & hashes",
    "href": "calculators/data-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "data",
      "units",
      "converter",
      "bandwidth",
      "checksum",
      "md5",
      "sha256"
    ],
    "input": null,
    "output": null,
    "related": [
      "unit-converter",
      "json-formatter",
      "qrcode"
    ],
    "subCategory": "Math & Units",
    "requiresNetwork": false
  },
  {
    "id": "date-calculator",
    "name": "Date Calculator",
    "desc": "Add, subtract, or diff dates",
    "href": "calculators/date-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "date",
      "days",
      "difference",
      "add"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Date & Time",
    "requiresNetwork": false
  },
  {
    "id": "discount-calculator",
    "name": "Discount Calculator",
    "desc": "Find sale price and savings",
    "href": "calculators/discount-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "discount",
      "sale",
      "percent",
      "savings"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "emi-calculator",
    "name": "EMI Calculator",
    "desc": "Loan EMI, interest, and amortization",
    "href": "calculators/emi-calculator/",
    "category": "calculators",
    "icon": null,
    "color": "#4F46E5",
    "featured": true,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "emi",
      "loan",
      "interest",
      "mortgage",
      "amortization"
    ],
    "input": null,
    "output": null,
    "related": [
      "sip-calculator",
      "salary-calculator",
      "compound-interest"
    ],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "fd-calculator",
    "name": "Fixed Deposit (FD)",
    "desc": "FD maturity amount and interest earned",
    "href": "calculators/fd-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "fd",
      "fixed deposit",
      "interest",
      "savings"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "financial-freedom-calculator",
    "name": "Financial Freedom Calculator",
    "desc": "Calculate your path to FIRE and plan your retirement.",
    "href": "calculators/financial-freedom-calculator/",
    "category": "calculators",
    "icon": null,
    "color": "#4F46E5",
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "fire",
      "financial freedom",
      "retirement",
      "savings",
      "net worth",
      "corpus"
    ],
    "input": null,
    "output": null,
    "related": [
      "emi-calculator",
      "sip-calculator",
      "retirement-calculator",
      "cagr-calculator",
      "safe-to-spend"
    ],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "gratuity-calculator",
    "name": "Gratuity Calculator",
    "desc": "Calculate Gratuity amount for employees covered and not covered under the Payment of Gratuity Act 1972.",
    "href": "calculators/gratuity-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "gratuity calculator",
      "gratuity act 1972",
      "severance",
      "employee benefits",
      "retirement"
    ],
    "input": null,
    "output": null,
    "related": [
      "salary-calculator",
      "income-tax",
      "nps-calculator"
    ],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "gst-calculator",
    "name": "GST Calculator",
    "desc": "Calculate GST (Add/Remove) for Indian tax slabs (5%, 12%, 18%, 28%) with CGST, SGST, and IGST breakdown.",
    "href": "calculators/gst-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "gst calculator",
      "calculate gst india",
      "gst tax calculator",
      "add gst remove gst",
      "reverse gst calculator",
      "cgst sgst igst calculator",
      "online gst calculator",
      "gst amount calculator"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "hra-calculator",
    "name": "HRA Exemption Calculator",
    "desc": "Calculate your House Rent Allowance (HRA) tax exemption limit based on Metro/Non-Metro rules.",
    "href": "calculators/hra-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "hra calculator",
      "house rent allowance",
      "tax exemption",
      "rent tax benefit",
      "income tax"
    ],
    "input": null,
    "output": null,
    "related": [
      "income-tax",
      "salary-calculator"
    ],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "income-tax",
    "name": "Income Tax Calculator",
    "desc": "Calculate income tax for FY 2025-26. Compare Old vs New regime and find the best tax-saving strategy.",
    "href": "calculators/income-tax/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "income tax",
      "tax calculator",
      "new regime",
      "old regime",
      "FY 2025-26",
      "salary tax",
      "tax india"
    ],
    "input": null,
    "output": null,
    "related": [
      "hra-calculator",
      "tds-calculator",
      "salary-calculator"
    ],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "inflation-calculator",
    "name": "Inflation Calculator",
    "desc": "Purchasing power over time",
    "href": "calculators/inflation-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "inflation",
      "purchasing power",
      "money",
      "value"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "invoice-generator",
    "name": "Invoice Generator",
    "desc": "Create professional branded invoices with custom logos, multiple templates, and automated tax calculations. 100% private and local.",
    "href": "calculators/invoice-generator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "invoice generator",
      "pro invoice maker",
      "free branded invoice",
      "gst invoice creator",
      "private invoice generator",
      "offline invoice maker",
      "custom logo invoice",
      "professional pdf invoice"
    ],
    "input": "none",
    "output": "pdf",
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "lumpsum-calculator",
    "name": "Lumpsum Calculator",
    "desc": "Future value of one-time investment",
    "href": "calculators/lumpsum-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "lumpsum",
      "investment",
      "future value",
      "wealth"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "mutual-fund-returns",
    "name": "Mutual Fund Returns",
    "desc": "Calculate absolute and annualized returns",
    "href": "calculators/mutual-fund-returns/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "mutual fund",
      "returns",
      "absolute",
      "annualized",
      "yield"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "nps-calculator",
    "name": "NPS Calculator",
    "desc": "Plan your retirement with the National Pension System. Estimate your corpus, monthly pension, and tax benefits.",
    "href": "calculators/nps-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "nps calculator",
      "national pension system",
      "retirement planning",
      "pension calculator",
      "80ccd"
    ],
    "input": null,
    "output": null,
    "related": [
      "retirement-calculator",
      "sip-calculator",
      "income-tax"
    ],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "numeral-converter",
    "name": "Numeral & Encoding Converter",
    "desc": "Universal encoding converter. Paste hex, binary, Base64, URL-encoded, HTML entities, Unicode escapes, or plain text. Auto-detect format and convert to all others instantly. Supports UTF-8, UTF-16, UTF-32, Base64, URL encoding, HTML entities, JavaScript/Python/CSS escapes, Morse code, ROT13, JWT decode, and more. 100% local — nothing leaves your browser.",
    "href": "calculators/numeral-converter/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "numeral converter",
      "encoding converter",
      "decoding tool",
      "hex to text",
      "text to hex",
      "binary to text",
      "text to binary",
      "base64 decode",
      "base64 encode",
      "base64 url-safe",
      "url decode",
      "url encode",
      "percent encoding",
      "html entity decode",
      "html entity encode",
      "unicode escape",
      "javascript escape",
      "utf-8 converter",
      "utf-16 converter",
      "utf-32 converter",
      "ascii converter",
      "morse code converter",
      "rot13",
      "caesar cipher",
      "atbash cipher",
      "jwt decoder",
      "jwt token decode",
      "hex decoder",
      "binary decoder",
      "byte converter",
      "character encoding"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Math & Units",
    "requiresNetwork": false
  },
  {
    "id": "percentage-calculator",
    "name": "Percentage Calculator",
    "desc": "Find percentages and ratios",
    "href": "calculators/percentage-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "percent",
      "percentage",
      "ratio"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Math & Units",
    "requiresNetwork": false
  },
  {
    "id": "ppf-calculator",
    "name": "PPF Calculator",
    "desc": "Public Provident Fund maturity & interest",
    "href": "calculators/ppf-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "ppf",
      "savings",
      "tax saving",
      "interest",
      "maturity"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "rd-calculator",
    "name": "Recurring Deposit (RD)",
    "desc": "RD maturity and interest calculation",
    "href": "calculators/rd-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "rd",
      "recurring deposit",
      "savings",
      "interest"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "retirement-calculator",
    "name": "Retirement Planner",
    "desc": "Corpus needed for your retirement",
    "href": "calculators/retirement-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "retirement",
      "planning",
      "pension",
      "corpus",
      "savings"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "safe-to-spend",
    "name": "Safe-to-Spend",
    "desc": "Daily budget planner",
    "href": "calculators/safe-to-spend/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "budget",
      "spending",
      "daily"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "salary-calculator",
    "name": "Salary Calculator",
    "desc": "Indian take-home salary breakdown",
    "href": "calculators/salary-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "salary",
      "ctc",
      "take home",
      "tax",
      "india"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "scientific-calculator",
    "name": "Scientific Calculator",
    "desc": "Advanced mathematical calculations",
    "href": "calculators/scientific-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "calculator",
      "scientific",
      "math",
      "trigonometry",
      "logarithm"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Math & Units",
    "requiresNetwork": false
  },
  {
    "id": "sip-calculator",
    "name": "SIP Calculator",
    "desc": "Project mutual-fund SIP returns",
    "href": "calculators/sip-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "sip",
      "investment",
      "mutual fund",
      "returns"
    ],
    "input": null,
    "output": null,
    "related": [
      "compound-interest",
      "emi-calculator"
    ],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "smart-converter",
    "name": "Smart Unit Converter",
    "desc": "Natural-language unit conversion",
    "href": "calculators/smart-converter/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "convert",
      "smart",
      "natural language"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Math & Units",
    "requiresNetwork": false
  },
  {
    "id": "standard-calculator",
    "name": "Standard Calculator",
    "desc": "Quick arithmetic calculator",
    "href": "calculators/standard-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "calculator",
      "math",
      "arithmetic"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Math & Units",
    "requiresNetwork": false
  },
  {
    "id": "stock-average-calculator",
    "name": "Stock Average",
    "desc": "Weighted average buy price for stocks",
    "href": "calculators/stock-average-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "stock",
      "average",
      "buy price",
      "trading",
      "investing"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "swp-calculator",
    "name": "SWP Calculator",
    "desc": "Systematic Withdrawal Plan planning",
    "href": "calculators/swp-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "swp",
      "withdrawal",
      "pension",
      "mutual fund",
      "income"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Financial",
    "requiresNetwork": false
  },
  {
    "id": "tds-calculator",
    "name": "TDS Calculator",
    "desc": "Calculate Tax Deducted at Source (TDS) for salary, rent, professional fees, and interest (194J, 194I, 194A, etc.).",
    "href": "calculators/tds-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "tds calculator",
      "tax deducted at source",
      "194J",
      "194A",
      "194I",
      "tds rate"
    ],
    "input": null,
    "output": null,
    "related": [
      "income-tax",
      "gst-calculator",
      "invoice-generator"
    ],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "time-calculator",
    "name": "Time Calculator",
    "desc": "Add or subtract hours and minutes",
    "href": "calculators/time-calculator/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "time",
      "duration",
      "hours",
      "minutes"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Date & Time",
    "requiresNetwork": false
  },
  {
    "id": "unit-converter",
    "name": "Unit Converter",
    "desc": "Length, weight, volume, and more",
    "href": "calculators/unit-converter/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "unit",
      "convert",
      "length",
      "weight",
      "volume",
      "metric"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Math & Units",
    "requiresNetwork": false
  },
  {
    "id": "utc-ist-converter",
    "name": "UTC ↔ IST",
    "desc": "Convert between UTC and IST",
    "href": "calculators/utc-ist-converter/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "utc",
      "ist",
      "timezone",
      "india"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Date & Time",
    "requiresNetwork": false
  },
  {
    "id": "work-hours",
    "name": "Work Hours",
    "desc": "Timesheet and overtime tracker",
    "href": "calculators/work-hours/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "work",
      "hours",
      "timesheet",
      "overtime"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Date & Time",
    "requiresNetwork": false
  },
  {
    "id": "world-clock",
    "name": "World Clock",
    "desc": "Track time across multiple cities with business hour indicators. Ideal for global teams.",
    "href": "calculators/world-clock/",
    "category": "calculators",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "time",
      "timezone",
      "clock",
      "utc",
      "global time",
      "time zone converter",
      "meeting planner"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Date & Time",
    "requiresNetwork": false
  }
] as any[];
