// Auto-generated.
import { ToolEntry } from '../types';
export const IMAGE_TOOLS: ToolEntry[] = [
  {
    "id": "bg-remover",
    "name": "Background Remover",
    "desc": "Remove image backgrounds locally",
    "href": "image-tools/bg-remover/",
    "category": "image",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "image",
      "background",
      "remove",
      "transparent"
    ],
    "input": "image",
    "output": "image",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "bulk-resizer",
    "name": "Bulk Image Resize",
    "desc": "Resize many images at once",
    "href": "image-tools/bulk-resizer/",
    "category": "image",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "image",
      "bulk",
      "batch",
      "resize"
    ],
    "input": "image",
    "output": "image",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "color-palette-extractor",
    "name": "Color Palette Extractor",
    "desc": "Extract dominant colors from an image.",
    "href": "image-tools/color-palette-extractor/",
    "category": "image",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "color",
      "palette",
      "extractor",
      "image",
      "design",
      "hex"
    ],
    "input": null,
    "output": null,
    "related": [
      "image-compress",
      "image-converter",
      "image-resizer"
    ],
    "subCategory": "Analysis",
    "requiresNetwork": false
  },
  {
    "id": "image-base64",
    "name": "Image to Base64",
    "desc": "Encode images as Base64 data URIs",
    "href": "image-tools/image-base64/",
    "category": "image",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "image",
      "base64",
      "data uri"
    ],
    "input": "image",
    "output": "text",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "image-compress",
    "name": "Image Compressor",
    "desc": "Reduce image file size",
    "href": "image-tools/image-compressor/",
    "category": "image",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "image",
      "compress",
      "jpg",
      "png",
      "webp"
    ],
    "input": "image",
    "output": "image",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "image-converter",
    "name": "Image Converter",
    "desc": "Convert between JPG, PNG, WebP, AVIF, and BMP",
    "href": "image-tools/image-converter/",
    "category": "image",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "image",
      "convert",
      "jpg",
      "png",
      "webp",
      "avif",
      "bmp"
    ],
    "input": "image",
    "output": "image",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "image-crop",
    "name": "Image Crop",
    "desc": "Crop images to ratio or freeform",
    "href": "image-tools/image-crop/",
    "category": "image",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "image",
      "crop",
      "trim"
    ],
    "input": "image",
    "output": "image",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "image-resizer",
    "name": "Image Resizer",
    "desc": "Resize images to exact dimensions",
    "href": "image-tools/image-resizer/",
    "category": "image",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "image",
      "resize",
      "dimensions"
    ],
    "input": "image",
    "output": "image",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "phone-mockup-generator",
    "name": "Phone Mockup Generator",
    "desc": "Wrap screenshots in realistic device frames",
    "href": "image-tools/phone-mockup-generator/",
    "category": "image",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "mockup",
      "phone",
      "iphone",
      "android",
      "screenshot",
      "presentation"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  }
] as any[];
