// Auto-generated.
import { ToolEntry } from '../types';
export const PDF_TOOLS: ToolEntry[] = [
  {
    "id": "compress-pdf",
    "name": "Compress PDF",
    "desc": "Reduce PDF file size",
    "href": "pdf-tools/compress-pdf/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "pdf",
      "compress",
      "reduce",
      "size"
    ],
    "input": "pdf",
    "output": "pdf",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "extract-images",
    "name": "Extract Images",
    "desc": "Pull images out of a PDF",
    "href": "pdf-tools/extract-images/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "pdf",
      "extract",
      "image"
    ],
    "input": "pdf",
    "output": "image",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "image-to-pdf",
    "name": "Image to PDF",
    "desc": "Convert images into a single PDF",
    "href": "pdf-tools/image-to-pdf/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "image",
      "jpg",
      "png",
      "pdf",
      "convert"
    ],
    "input": "image",
    "output": "pdf",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "lock-unlock-pdf",
    "name": "Lock / Unlock PDF",
    "desc": "Add or remove PDF passwords",
    "href": "pdf-tools/lock-unlock/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "pdf",
      "password",
      "lock",
      "unlock",
      "encrypt"
    ],
    "input": "pdf",
    "output": "pdf",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "merge-pdf",
    "name": "Merge PDF",
    "desc": "Combine multiple PDFs into one",
    "href": "pdf-tools/merge-pdf/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "pdf",
      "merge",
      "combine",
      "join"
    ],
    "input": "pdf",
    "output": "pdf",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "page-numbering",
    "name": "Page Numbering",
    "desc": "Add page numbers to PDF",
    "href": "pdf-tools/page-numbering/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "pdf",
      "page",
      "number"
    ],
    "input": "pdf",
    "output": "pdf",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "pdf-to-word",
    "name": "PDF to Word",
    "desc": "Convert PDF text to editable Word",
    "href": "pdf-tools/pdf-to-word/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "pdf",
      "word",
      "docx",
      "convert"
    ],
    "input": "pdf",
    "output": "text",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "rotate-pdf",
    "name": "Rotate PDF",
    "desc": "Rotate one or all pages",
    "href": "pdf-tools/rotate-pdf/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "pdf",
      "rotate",
      "flip",
      "orientation"
    ],
    "input": "pdf",
    "output": "pdf",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "split-pdf",
    "name": "Split PDF",
    "desc": "Extract pages from a PDF",
    "href": "pdf-tools/split-pdf/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "pdf",
      "split",
      "extract",
      "pages"
    ],
    "input": "pdf",
    "output": "pdf",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "watermark-pdf",
    "name": "Watermark PDF",
    "desc": "Add text or image watermark",
    "href": "pdf-tools/watermark-pdf/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "pdf",
      "watermark",
      "stamp"
    ],
    "input": "pdf",
    "output": "pdf",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "word-to-pdf",
    "name": "Word to PDF",
    "desc": "Convert Word documents (.docx) to PDF format.",
    "href": "pdf-tools/word-to-pdf/",
    "category": "pdf",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "word to pdf",
      "docx to pdf",
      "convert word",
      "pdf converter"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Conversion",
    "requiresNetwork": false
  }
] as any[];
