// Auto-generated.
import { ToolEntry } from '../types';
export const PRODUCTIVITY_TOOLS: ToolEntry[] = [
  {
    "id": "calendar",
    "name": "Calendar",
    "desc": "Professional, local-first calendar with Tamil mode support.",
    "href": "productivity/calendar/",
    "category": "productivity",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "calendar",
      "productivity",
      "tamil calendar",
      "events",
      "schedule",
      "local-first"
    ],
    "input": "none",
    "output": "none",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "chart-generator",
    "name": "Chart & Graph Generator",
    "desc": "Create beautiful charts from your data",
    "href": "productivity/chart-generator/",
    "category": "productivity",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-06-05",
    "keywords": [
      "chart",
      "graph",
      "bar chart",
      "pie chart",
      "line graph",
      "data visualization"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "notes",
    "name": "KV Secure Notes",
    "desc": "Zero-transmission, AES-256 encrypted private notes with Markdown and checklists.",
    "href": "productivity/notes/",
    "category": "productivity",
    "icon": "StickyNote",
    "color": "#4F46E5",
    "featured": true,
    "popular": true,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "notes",
      "notebook",
      "private notes",
      "offline notes",
      "markdown notes",
      "checklist"
    ],
    "input": "text",
    "output": "text",
    "related": [
      "calendar",
      "task-reminder",
      "markdown"
    ],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "pomodoro-timer",
    "name": "Pomodoro Timer",
    "desc": "A simple, customizable timer to help you focus.",
    "href": "productivity/pomodoro-timer/",
    "category": "productivity",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "pomodoro",
      "timer",
      "focus",
      "productivity",
      "stopwatch"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Time Management",
    "requiresNetwork": false
  },
  {
    "id": "text-case-converter",
    "name": "Text Case Converter",
    "desc": "Convert text between UPPERCASE, lowercase, Title Case, camelCase, and more.",
    "href": "productivity/text-case-converter/",
    "category": "productivity",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "text converter",
      "uppercase",
      "lowercase",
      "camelcase",
      "snake_case"
    ],
    "input": "text",
    "output": "text",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "text-sorter-deduper",
    "name": "Text Sorter & Deduplicator",
    "desc": "Sort and remove duplicates from text",
    "href": "productivity/text-sorter-deduper/",
    "category": "productivity",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "sort",
      "deduplicate",
      "text",
      "lines",
      "alphabetical"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "timezone-converter",
    "name": "Time Zone Converter",
    "desc": "Compare and convert time between multiple global time zones. Real-time offsets and DST support.",
    "href": "productivity/timezone-converter/",
    "category": "productivity",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "timezone",
      "converter",
      "world clock",
      "time",
      "iana",
      "dst",
      "meeting planner",
      "utc converter",
      "local time"
    ],
    "input": null,
    "output": null,
    "related": [
      "world-clock",
      "utc-ist-converter",
      "date-calculator",
      "time-calculator"
    ],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "typing-speed-test",
    "name": "Typing Speed Test",
    "desc": "Test and improve your typing WPM",
    "href": "productivity/typing-speed-test/",
    "category": "productivity",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "typing test",
      "wpm",
      "accuracy",
      "keyboard",
      "typing speed"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "wifi-qr-code",
    "name": "WiFi QR Code Generator",
    "desc": "Generate QR code to connect to WiFi",
    "href": "productivity/wifi-qr-code/",
    "category": "productivity",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "wifi",
      "qr code",
      "generator",
      "wpa",
      "wep",
      "network"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "word-counter",
    "name": "Word Counter",
    "desc": "Count words, characters, sentences, and paragraphs in real-time.",
    "href": "productivity/word-counter/",
    "category": "productivity",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "word count",
      "character count",
      "reading time",
      "text analysis"
    ],
    "input": "text",
    "output": "none",
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  }
] as any[];
