import { ToolEntry } from '../types';

export const SECURITY_TOOLS: ToolEntry[] = [
  {
    "id": "iban-validator",
    "name": "IBAN & SWIFT Code Validator",
    "desc": "Validate International Bank Account Numbers (IBAN) using ISO 13616 Mod-97 and verify SWIFT/BIC codes.",
    "href": "security-tools/iban-validator/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["iban validator", "swift code", "bic code", "bank account validation", "finacle"],
    "input": null,
    "output": null,
    "related": ["luhn-validator", "card-masker"],
    "subCategory": "Financial & Payment Protocols",
    "requiresNetwork": false
  },
  {
    "id": "card-masker",
    "name": "Credit Card & PAN Masker",
    "desc": "Mask primary account numbers (PAN) for PCI-DSS compliance and secure logging (First 6 / Last 4 formatting).",
    "href": "security-tools/card-masker/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["pan masker", "card masking", "pci dss", "credit card masker", "sanitization"],
    "input": null,
    "output": null,
    "related": ["luhn-validator", "iban-validator"],
    "subCategory": "Financial & Payment Protocols",
    "requiresNetwork": false
  },
  {
    "id": "iso8583-bitmap-decoder",
    "name": "ISO 8583 Bitmap Decoder",
    "desc": "Decode ISO 8583 primary and secondary hex bitmaps into field presence indicators, or build hex bitmaps visually.",
    "href": "security-tools/iso8583-bitmap-decoder/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["iso 8583", "bitmap decoder", "iso8583", "banking protocol", "finacle", "payment bitmap"],
    "input": null,
    "output": null,
    "related": ["iso8583-message-parser", "tlv-parser", "luhn-validator"],
    "subCategory": "Financial & Payment Protocols",
    "requiresNetwork": false
  },
  {
    "id": "iso8583-message-parser",
    "name": "ISO 8583 Message Parser",
    "desc": "Parse financial ISO 8583 payment messages, MTI, bitmaps, and data elements directly in your browser.",
    "href": "security-tools/iso8583-message-parser/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["iso 8583 parser", "mti parser", "iso8583 message", "payment parser", "finacle"],
    "input": null,
    "output": null,
    "related": ["iso8583-bitmap-decoder", "tlv-parser", "jwt-decoder"],
    "subCategory": "Financial & Payment Protocols",
    "requiresNetwork": false
  },
  {
    "id": "tlv-parser",
    "name": "EMV TLV Parser",
    "desc": "Parse Tag-Length-Value (TLV / BER-TLV) hex data streams from EMV chip cards and payment terminals.",
    "href": "security-tools/tlv-parser/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["tlv parser", "emv tlv", "ber-tlv", "iso 7816", "chip card", "payment tag"],
    "input": null,
    "output": null,
    "related": ["iso8583-message-parser", "iso8583-bitmap-decoder", "asn1-parser"],
    "subCategory": "Financial & Payment Protocols",
    "requiresNetwork": false
  },
  {
    "id": "cipher-tools",
    "name": "Text Cipher Tools",
    "desc": "Encrypt and decrypt text using classic ciphers like Caesar, Vigenère, ROT13, XOR, and Morse Code natively in your browser.",
    "href": "security-tools/cipher-tools/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": ["cipher", "encryption", "decryption", "caesar cipher", "vigenere", "rot13", "xor cipher", "morse code"],
    "input": null,
    "output": null,
    "related": ["base64", "hash-generator", "url-encoder"],
    "subCategory": "Classic Ciphers",
    "requiresNetwork": false
  },
  {
    "id": "csp-builder",
    "name": "CSP Builder",
    "desc": "Visual Content Security Policy (CSP) generator. Build, analyze, and export strict CSP headers to protect against XSS and injection attacks.",
    "href": "security-tools/csp-builder/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": ["csp", "content security policy", "csp generator", "xss protection", "security headers", "csp evaluator"],
    "input": null,
    "output": null,
    "related": ["meta-tags", "robots-txt", "hmac-generator"],
    "subCategory": "Web Security",
    "requiresNetwork": false
  },
  {
    "id": "hash-generator",
    "name": "Hash Generator",
    "desc": "Generate MD5, SHA-1, SHA-224, SHA-256, SHA-384, SHA-512 cryptographic digests for text and files.",
    "href": "security-tools/hash-generator/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": ["hash", "md5", "sha1", "sha224", "sha256", "sha384", "sha512", "checksum"],
    "input": null,
    "output": null,
    "related": ["hmac-generator", "directory-manifest", "hash-map-visualizer"],
    "subCategory": "Hashing",
    "requiresNetwork": false
  },
  {
    "id": "directory-manifest",
    "name": "Directory Hash Manifest",
    "desc": "Compute MD5, SHA-256, or SHA-512 hashes for all files in a folder and generate a verification manifest.",
    "href": "security-tools/directory-manifest/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["directory manifest", "folder hash", "batch checksum", "sha256sum", "file verification"],
    "input": null,
    "output": null,
    "related": ["hash-generator", "hmac-generator", "validate"],
    "subCategory": "Hashing",
    "requiresNetwork": false
  },
  {
    "id": "hmac-generator",
    "name": "HMAC Generator",
    "desc": "Generate Hash-based Message Authentication Codes (HMAC) using SHA-256, SHA-512, and other algorithms.",
    "href": "security-tools/hmac-generator/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "new",
    "lastAdded": null,
    "keywords": ["hmac", "mac", "hash authentication", "sha256 hmac", "signature generator", "jwt signature"],
    "input": null,
    "output": null,
    "related": ["hash-generator", "base64", "jwt-decoder"],
    "subCategory": "Hashing",
    "requiresNetwork": false
  },
  {
    "id": "aes-encrypt-decrypt",
    "name": "AES Encrypt / Decrypt",
    "desc": "Encrypt and decrypt text using AES-256-GCM or AES-256-CBC with PBKDF2 key derivation.",
    "href": "security-tools/aes-encrypt-decrypt/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["aes encrypt", "aes decrypt", "aes-gcm", "aes-256", "symmetric encryption"],
    "input": null,
    "output": null,
    "related": ["rsa-key-generator", "rsa-encrypt-decrypt", "pbkdf2-generator"],
    "subCategory": "Encryption & Key Derivation",
    "requiresNetwork": false
  },
  {
    "id": "rsa-key-generator",
    "name": "RSA Key Generator",
    "desc": "Generate RSA Public & Private keypairs (1024, 2048, 3072, 4096-bit) in PEM format 100% locally.",
    "href": "security-tools/rsa-key-generator/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["rsa keygen", "rsa generator", "public key", "private key", "pem key"],
    "input": null,
    "output": null,
    "related": ["rsa-encrypt-decrypt", "rsa-sign-verify", "public-key-inspector"],
    "subCategory": "Asymmetric Keys",
    "requiresNetwork": false
  },
  {
    "id": "rsa-encrypt-decrypt",
    "name": "RSA Encrypt / Decrypt",
    "desc": "Encrypt text with an RSA Public Key (OAEP padding) and decrypt with an RSA Private Key.",
    "href": "security-tools/rsa-encrypt-decrypt/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["rsa encrypt", "rsa decrypt", "rsa oaep", "asymmetric encryption"],
    "input": null,
    "output": null,
    "related": ["rsa-key-generator", "rsa-sign-verify", "aes-encrypt-decrypt"],
    "subCategory": "Encryption & Key Derivation",
    "requiresNetwork": false
  },
  {
    "id": "rsa-sign-verify",
    "name": "RSA Sign / Verify",
    "desc": "Create RSASSA-PKCS1-v1_5 digital signatures with a private key and verify them with a public key.",
    "href": "security-tools/rsa-sign-verify/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["rsa sign", "rsa verify", "digital signature", "pkcs1"],
    "input": null,
    "output": null,
    "related": ["rsa-key-generator", "ecdsa-sign", "hmac-generator"],
    "subCategory": "Digital Signatures",
    "requiresNetwork": false
  },
  {
    "id": "ecdsa-sign",
    "name": "ECDSA Sign & Verify",
    "desc": "Generate Elliptic Curve keypairs (P-256, P-384, P-521), create ECDSA signatures, and verify messages.",
    "href": "security-tools/ecdsa-sign/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["ecdsa", "elliptic curve signature", "p-256", "secp256r1", "ec signature"],
    "input": null,
    "output": null,
    "related": ["ecdh-key-exchange", "rsa-sign-verify", "jwt-decoder"],
    "subCategory": "Digital Signatures",
    "requiresNetwork": false
  },
  {
    "id": "ecdh-key-exchange",
    "name": "ECDH Key Exchange",
    "desc": "Simulate Elliptic Curve Diffie-Hellman (ECDH) key exchange to derive shared secrets.",
    "href": "security-tools/ecdh-key-exchange/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["ecdh", "diffie hellman", "key exchange", "shared secret"],
    "input": null,
    "output": null,
    "related": ["ecdsa-sign", "hkdf-generator", "aes-encrypt-decrypt"],
    "subCategory": "Asymmetric Keys",
    "requiresNetwork": false
  },
  {
    "id": "pbkdf2-generator",
    "name": "PBKDF2 Generator",
    "desc": "Derive keys using Password-Based Key Derivation Function 2 (PBKDF2) with custom salt and iterations.",
    "href": "security-tools/pbkdf2-generator/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["pbkdf2", "key derivation", "password hash", "salt"],
    "input": null,
    "output": null,
    "related": ["hkdf-generator", "aes-encrypt-decrypt", "hash-generator"],
    "subCategory": "Encryption & Key Derivation",
    "requiresNetwork": false
  },
  {
    "id": "hkdf-generator",
    "name": "HKDF Generator",
    "desc": "Derive keys using HMAC-based Extract-and-Expand Key Derivation Function (HKDF, RFC 5869).",
    "href": "security-tools/hkdf-generator/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["hkdf", "hmac key derivation", "rfc 5869", "key expansion"],
    "input": null,
    "output": null,
    "related": ["pbkdf2-generator", "ecdh-key-exchange", "hmac-generator"],
    "subCategory": "Encryption & Key Derivation",
    "requiresNetwork": false
  },
  {
    "id": "pem-viewer",
    "name": "PEM Viewer & Inspector",
    "desc": "Inspect PEM blocks, decode Base64 payloads, analyze ASN.1 structure, and format raw DER keys.",
    "href": "security-tools/pem-viewer/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["pem viewer", "asn1 parser", "der decoder", "pem block"],
    "input": null,
    "output": null,
    "related": ["x509-viewer", "csr-generator", "public-key-inspector"],
    "subCategory": "Certificates & Keys Inspection",
    "requiresNetwork": false
  },
  {
    "id": "csr-generator",
    "name": "CSR Generator & Inspector",
    "desc": "Generate PKCS#10 Certificate Signing Requests (CSR) and private keys directly inside your browser.",
    "href": "security-tools/csr-generator/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["csr generator", "certificate signing request", "pkcs10", "ssl csr"],
    "input": null,
    "output": null,
    "related": ["x509-viewer", "rsa-key-generator", "pem-viewer"],
    "subCategory": "Certificates & Keys Inspection",
    "requiresNetwork": false
  },
  {
    "id": "x509-viewer",
    "name": "X.509 Certificate Viewer",
    "desc": "Inspect SSL/TLS X.509 certificates, view Subject, Issuer, Validity periods, Extensions, and Fingerprints.",
    "href": "security-tools/x509-viewer/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["x509 viewer", "ssl certificate decoder", "cert viewer", "tls certificate"],
    "input": null,
    "output": null,
    "related": ["csr-generator", "pem-viewer", "public-key-inspector"],
    "subCategory": "Certificates & Keys Inspection",
    "requiresNetwork": false
  },
  {
    "id": "public-key-inspector",
    "name": "Public Key Inspector",
    "desc": "Inspect SPKI / RSA / EC public keys, calculate fingerprints, and verify public key parameters.",
    "href": "security-tools/public-key-inspector/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["public key inspector", "spki", "rsa public key", "key fingerprint"],
    "input": null,
    "output": null,
    "related": ["private-key-checker", "rsa-key-generator", "x509-viewer"],
    "subCategory": "Certificates & Keys Inspection",
    "requiresNetwork": false
  },
  {
    "id": "private-key-checker",
    "name": "Private Key Checker",
    "desc": "Check PKCS#8 & PKCS#1 private key syntax, structure, bit lengths, and security parameters 100% locally.",
    "href": "security-tools/private-key-checker/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["private key checker", "pkcs8", "pkcs1", "rsa private key"],
    "input": null,
    "output": null,
    "related": ["public-key-inspector", "rsa-key-generator", "pem-viewer"],
    "subCategory": "Certificates & Keys Inspection",
    "requiresNetwork": false
  },
  {
    "id": "jwt-decoder",
    "name": "JWT Decoder & Inspector",
    "desc": "Inspect JSON Web Tokens (JWT), parse headers & claims, and verify HMAC/RSA/ECDSA signatures.",
    "href": "security-tools/jwt-decoder/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": true,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": ["jwt", "token", "json web token", "jwt decode", "jwt verify"],
    "input": null,
    "output": null,
    "related": ["oauth-token-decoder", "base64url-converter", "hmac-generator"],
    "subCategory": "Tokens & Encodings",
    "requiresNetwork": false
  },
  {
    "id": "oauth-token-decoder",
    "name": "OAuth 2.0 Token Decoder",
    "desc": "Inspect OAuth 2.0 access tokens, identity tokens, scopes, claims, client IDs, and expiration status.",
    "href": "security-tools/oauth-token-decoder/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["oauth token decoder", "access token", "oidc token", "bearer token"],
    "input": null,
    "output": null,
    "related": ["jwt-decoder", "saml-decoder", "base64url-converter"],
    "subCategory": "Tokens & Encodings",
    "requiresNetwork": false
  },
  {
    "id": "saml-decoder",
    "name": "SAML Decoder",
    "desc": "Decode Base64/URL encoded SAML2 Requests and Responses into formatted XML with extracted attributes.",
    "href": "security-tools/saml-decoder/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["saml decoder", "saml request", "saml response", "authnrequest", "saml xml"],
    "input": null,
    "output": null,
    "related": ["oauth-token-decoder", "jwt-decoder", "base64url-converter"],
    "subCategory": "Tokens & Encodings",
    "requiresNetwork": false
  },
  {
    "id": "base64url-converter",
    "name": "Base64URL Converter",
    "desc": "Bi-directional Base64URL (RFC 4648) encoder & decoder for JWTs, tokens, and web URLs.",
    "href": "security-tools/base64url-converter/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-07-05",
    "keywords": ["base64url", "rfc 4648", "url safe base64", "jwt encoding"],
    "input": null,
    "output": null,
    "related": ["base64", "jwt-decoder", "url-encoder"],
    "subCategory": "Tokens & Encodings",
    "requiresNetwork": false
  },
  {
    "id": "html-entities",
    "name": "HTML Entities",
    "desc": "Convert characters to HTML entities",
    "href": "security-tools/html-entities/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": ["html", "entities", "escape"],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": "Encoding Utilities",
    "requiresNetwork": false
  },
  {
    "id": "password-generator",
    "name": "Password Generator",
    "desc": "Strong, random passwords",
    "href": "security-tools/password-generator/",
    "category": "security",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": ["password", "random", "strong", "generator"],
    "input": null,
    "output": null,
    "related": ["hash-generator", "base64"],
    "subCategory": "Generators",
    "requiresNetwork": false
  }
] as any[];
