// Auto-generated.
import { ToolEntry } from '../types';
export const SEO_TOOLS: ToolEntry[] = [
  {
    "id": "image-seo",
    "name": "Image SEO & File Renamer",
    "desc": "Generate SEO alt text and optimized filenames for images, PDF, and documents.",
    "href": "seo-tools/image-seo/",
    "category": "seo",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "image seo",
      "alt text generator",
      "file renamer",
      "seo filename",
      "pdf renamer",
      "docx renamer",
      "image optimization",
      "accessibility"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "meta-tags",
    "name": "Meta Tags Generator",
    "desc": "Build SEO meta tags",
    "href": "seo-tools/meta-tags/",
    "category": "seo",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "seo",
      "meta",
      "tags",
      "head"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "og-preview",
    "name": "OG Preview",
    "desc": "Preview Open Graph cards",
    "href": "seo-tools/og-preview/",
    "category": "seo",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "og",
      "open graph",
      "preview",
      "social"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "robots-txt",
    "name": "robots.txt Builder",
    "desc": "Create robots.txt files",
    "href": "seo-tools/robots-txt/",
    "category": "seo",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "robots",
      "txt",
      "crawl",
      "seo"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "seo-title",
    "name": "SEO Title Tester",
    "desc": "Score SEO title tags",
    "href": "seo-tools/seo-title/",
    "category": "seo",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "seo",
      "title",
      "tag",
      "score"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "sitemap-generator",
    "name": "Sitemap Generator",
    "desc": "Build XML sitemaps",
    "href": "seo-tools/sitemap-generator/",
    "category": "seo",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "sitemap",
      "xml",
      "seo"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "slug-generator",
    "name": "Slug Generator",
    "desc": "URL-safe slugs from text",
    "href": "seo-tools/slug-generator/",
    "category": "seo",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "slug",
      "url",
      "permalink",
      "seo"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  }
] as any[];
