// Auto-generated.
import { ToolEntry } from '../types';
export const UTILITIES_TOOLS: ToolEntry[] = [
  {
    "id": "barcode-scanner",
    "name": "Barcode & QR Scanner",
    "desc": "Scan barcodes and QR codes using camera",
    "href": "utilities/barcode-scanner/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": "2026-06-05",
    "keywords": [
      "barcode",
      "qr scanner",
      "upc",
      "ean",
      "scan"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "grammar-checker",
    "name": "Grammar Checker",
    "desc": "Spot common writing errors",
    "href": "utilities/grammar-checker/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "grammar",
      "spelling",
      "writing"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "internet-speed-test",
    "name": "Speed Tester",
    "desc": "Measure your internet connection speed",
    "href": "utilities/internet-speed-test/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "speed",
      "test",
      "internet",
      "wifi",
      "ping",
      "latency"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": true
  },
  {
    "id": "markdown",
    "name": "Markdown Editor",
    "desc": "Professional Markdown editor with live GitHub-style preview, Mermaid diagrams, and high-performance export options.",
    "href": "utilities/markdown/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "markdown",
      "md",
      "editor",
      "preview",
      "mermaid",
      "diagrams",
      "export pdf",
      "export docx"
    ],
    "input": null,
    "output": null,
    "related": [
      "html-viewer",
      "code-minifier",
      "text-utility",
      "word-counter"
    ],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "mic-camera-tester",
    "name": "Mic & Camera Tester",
    "desc": "Test your microphone and camera",
    "href": "utilities/mic-camera-tester/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "new",
    "lastAdded": null,
    "keywords": [
      "mic test",
      "camera test",
      "webcam",
      "microphone",
      "online meeting"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "qrcode",
    "name": "QR Code Generator",
    "desc": "Make QR codes for URLs, text, Wi-Fi",
    "href": "utilities/qrcode/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": true,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "qr",
      "qrcode",
      "barcode"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "split-copy",
    "name": "Split & Copy",
    "desc": "Break long text into chunks",
    "href": "utilities/split-copy/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "split",
      "copy",
      "text",
      "chunks"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "task-reminder",
    "name": "Task Reminder",
    "desc": "Lightweight private to-do list",
    "href": "utilities/task-reminder/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "task",
      "todo",
      "reminder",
      "list"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "text-utility",
    "name": "Text Utility",
    "desc": "Clean, case convert, count words",
    "href": "utilities/text-utility/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "text",
      "case",
      "word count",
      "clean"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "url-cleaner",
    "name": "URL Cleaner",
    "desc": "Strip tracking parameters",
    "href": "utilities/url-cleaner/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "url",
      "clean",
      "tracking",
      "utm"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  },
  {
    "id": "validate",
    "name": "File Validator",
    "desc": "Validate file size and type",
    "href": "utilities/validate/",
    "category": "utilities",
    "icon": null,
    "color": null,
    "featured": false,
    "popular": false,
    "status": "stable",
    "lastAdded": null,
    "keywords": [
      "validate",
      "file",
      "size",
      "type"
    ],
    "input": null,
    "output": null,
    "related": [],
    "subCategory": null,
    "requiresNetwork": false
  }
] as any[];
