import { Metadata } from 'next';
import { CATEGORIES } from '@/src/tool-registry';
import { ToolShell } from '@/components/ui/ToolShell';
import { generateToolMetadata } from '@/src/lib/seo';
import { LearningHub, LearningSection } from '@/src/components/els/LearningHub';
import { QuizWidget } from '@/src/components/els/QuizWidget';
import EcdhClientWrapper from './EcdhClientWrapper';

const toolId = 'ecdh-key-exchange';
const cat = CATEGORIES.find(c => c.id === 'security');

export const metadata: Metadata = generateToolMetadata(toolId);

export default function Page() {
  return (
    <ToolShell
      title="ECDH Key Exchange Demo"
      description="Simulate Elliptic Curve Diffie-Hellman (ECDH) key exchange between Party A and Party B to derive a matching shared secret."
      category={cat}
      toolId={toolId}
    >
      <EcdhClientWrapper />

      <LearningHub title="Understanding Key Exchange (ECDH)">
        <LearningSection type="architecture" title="The Problem: Agreeing on a Secret">
          <p>When you connect to your bank's website using HTTPS, your browser and the bank's server need to encrypt data using a fast symmetric cipher like AES. But AES requires both sides to possess the exact same secret key. How do they agree on a secret key over the open Internet without a hacker intercepting it?</p>
        </LearningSection>
        
        <LearningSection type="security" title="The Magic of ECDH">
          <p>The solution is a mathematical magic trick called Elliptic Curve Diffie-Hellman (ECDH). The process works like this:</p>
          <ol className="list-decimal pl-5 mt-2 space-y-2">
            <li><strong>Party A</strong> generates a private key and mathematically derives a public key from it. They send the public key to Party B over the open internet.</li>
            <li><strong>Party B</strong> does the exact same thing, sending their public key to Party A.</li>
            <li>Here is the magic: Party A takes their own Private Key, and multiplies it by Party B's Public Key. Party B takes their own Private Key, and multiplies it by Party A's Public Key.</li>
          </ol>
          <p className="mt-2">Due to the algebraic properties of Elliptic Curves, both parties will independently arrive at the exact same number (the <strong>Shared Secret</strong>). Even if a hacker intercepts both public keys in transit, they cannot calculate the shared secret without possessing at least one of the private keys.</p>
        </LearningSection>

        <LearningSection type="api" title="Never Use the Raw Secret">
          <p>The shared secret generated by ECDH is mathematically secure, but it is not uniformly random (it has structural bias). <strong>You must never use the raw ECDH output directly as an AES key.</strong></p>
          <p className="mt-2">Instead, the raw shared secret is passed through a Key Derivation Function (specifically <strong>HKDF</strong>) to "extract and expand" it into perfectly uniform cryptographic keys suitable for AES encryption.</p>
        </LearningSection>

        <LearningSection type="failures" title="Man-in-the-Middle (MITM) Attacks">
          <p>ECDH solves the problem of eavesdropping, but it <strong>does not authenticate</strong> the parties. A hacker could intercept Party A's public key, swap it with their own, and do the same to Party B. Now the hacker has established two separate secure channels and can read everything!</p>
          <p className="mt-2">This is why ECDH is always paired with <strong>Digital Signatures (like ECDSA or RSA)</strong>. During the TLS handshake, the server signs its ECDH public key using the private key associated with its SSL certificate, proving its identity and neutralizing MITM attacks.</p>
        </LearningSection>

        <LearningSection type="general" title="Check Your Knowledge" fullWidth>
          <QuizWidget 
            questions={[
              {
                question: "If Eve intercepts the public keys sent by both Alice and Bob during an ECDH exchange, what can she do?",
                options: [
                  "She can instantly calculate the shared secret.",
                  "She can deduce Alice's private key.",
                  "She has the public keys, but without at least one private key, she cannot calculate the shared secret.",
                  "She can decrypt the past AES messages they sent."
                ],
                correctIndex: 2,
                explanation: "The math of Diffie-Hellman ensures that knowing both public components is insufficient to calculate the shared secret. One of the private keys is required."
              },
              {
                question: "Why shouldn't you use the raw output of ECDH directly as an AES encryption key?",
                options: [
                  "Because it is too short to be an AES key.",
                  "Because it has structural mathematical bias and is not perfectly random.",
                  "Because it is formatted as Base64, which AES doesn't accept.",
                  "Because AES only accepts passwords, not keys."
                ],
                correctIndex: 1,
                explanation: "The raw shared secret is a point on an elliptic curve, not a uniformly random bit string. HKDF is used to 'smooth out' this output into perfect cryptographic keys."
              }
            ]}
          />
        </LearningSection>
      </LearningHub>
    </ToolShell>
  );
}
