export const memoryMatch = {
    id: 'memory-match',
    name: 'Memory Match',
    desc: 'Flip cards and match pairs. A classic memory-training game with best-score tracking.',
    href: '/break-time-tools/memory-match/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-09',
    keywords: ['memory match', 'card flip', 'pairs', 'concentration', 'brain training', 'game', 'fun'],
    input: null,
    output: null,
    related: ['tic-tac-toe', 'game-2048'],
    subCategory: 'Brain Training',
    requiresNetwork: false,
    difficulty: 'beginner',
    priority: 0.4,
    schemaType: 'WebApplication',
};
