export const snakeGame = {
    id: 'snake-game',
    name: 'Snake Game',
    desc: 'Play the classic retro Snake game. Eat food, grow longer, and set new high scores entirely in your browser.',
    href: '/break-time-tools/snake-game/',
    category: 'break-time',
    icon: null,
    color: '#8B5CF6',
    featured: false,
    popular: false,
    status: 'new',
    lastAdded: '2026-07-11',
    keywords: ['snake', 'arcade', 'retro', 'classic game', 'brain break', 'fun', 'offline'],
    input: null,
    output: null,
    related: ['game-2048', 'reaction-time', 'tic-tac-toe'],
    subCategory: 'Games',
    requiresNetwork: false,
    difficulty: 'intermediate',
    priority: 0.8,
    schemaType: 'WebApplication',
};
