import fs from 'fs';
import path from 'path';

import { ToolEntry } from '../src/registry/types';

async function main() {
  const toolsDir = path.resolve(process.cwd(), 'src/registry/tools');
  const files = fs.readdirSync(toolsDir).filter(f => f.endsWith('.ts'));

  const coreTools: ToolEntry[] = [];

  for (const file of files) {
    const filePath = path.join(toolsDir, file);
    try {
      // Dynamic import of tool config
      const module = await import(filePath);
      const exportName = Object.keys(module)[0];
      if (!exportName) continue;
      
      const tool = module[exportName];
      if (tool && tool.id) {
        // Exclude large content fields or optional fields not needed on home/search
        const coreTool = {
          id: tool.id,
          name: tool.name,
          desc: tool.desc,
          href: tool.href,
          category: tool.category,
          icon: tool.icon || null,
          color: tool.color || null,
          featured: tool.featured || false,
          popular: tool.popular || false,
          status: tool.status || 'stable',
          lastAdded: tool.lastAdded || null,
          keywords: tool.keywords || [],
          input: tool.input || null,
          output: tool.output || null,
          related: tool.related || [],
          subCategory: tool.subCategory || null,
          requiresNetwork: tool.requiresNetwork || false
        };
        coreTools.push(coreTool);
      }
    } catch (err) {
      console.error(`Error loading tool config ${file}:`, err);
    }
  }

  // Write core-registry.ts
  const content = `// This file is auto-generated by scripts/generate-registries.ts. Do not edit directly.
import { ToolEntry } from './types';

export const CORE_TOOLS: ToolEntry[] = ${JSON.stringify(coreTools, null, 2)};
`;

  const outputPath = path.resolve(process.cwd(), 'src/registry/core-registry.ts');
  fs.writeFileSync(outputPath, content);
  
  // Generate llms.txt for AI agents
  const llmsContent = `# KaruviLab

> KaruviLab is a privacy-first, zero-server-upload collection of local browser tools. This document provides instructions and metadata for AI Agents navigating the site.

## Navigation & Architecture
- The site uses Next.js with React 19.
- Tools execute locally in the browser using WebAssembly and Web Workers. No files are uploaded to servers.
- The UI follows WCAG 2.2 AA accessibility standards.

## Available Tools

${coreTools.map(t => `- [${t.name}](https://karuvilab.com/${t.href}): ${t.desc}`).join('\n')}
`;

  const llmsPath = path.resolve(process.cwd(), 'public/llms.txt');
  fs.writeFileSync(llmsPath, llmsContent);

  console.log(`✅ Core registry compiled successfully with ${coreTools.length} tools.`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
