import { ToolEntry } from '../types';

export const numeralConverter: ToolEntry = {
  "id": "numeral-converter",
  "name": "Numeral & Encoding Converter",
  "desc": "Universal encoding converter. Paste hex, binary, Base64, URL-encoded, HTML entities, Unicode escapes, or plain text. Auto-detect format and convert to all others instantly. Supports UTF-8, UTF-16, UTF-32, Base64, URL encoding, HTML entities, JavaScript/Python/CSS escapes, Morse code, ROT13, JWT decode, and more. 100% local — nothing leaves your browser.",
  "href": "/calculators/numeral-converter/",
  "category": "calculators",
  "subCategory": "Math & Units",
  "keywords": [
    "numeral converter",
    "encoding converter",
    "decoding tool",
    "hex to text",
    "text to hex",
    "binary to text",
    "text to binary",
    "base64 decode",
    "base64 encode",
    "base64 url-safe",
    "url decode",
    "url encode",
    "percent encoding",
    "html entity decode",
    "html entity encode",
    "unicode escape",
    "javascript escape",
    "utf-8 converter",
    "utf-16 converter",
    "utf-32 converter",
    "ascii converter",
    "morse code converter",
    "rot13",
    "caesar cipher",
    "atbash cipher",
    "jwt decoder",
    "jwt token decode",
    "hex decoder",
    "binary decoder",
    "byte converter",
    "character encoding"
  ],
  "searchIntent": "transactional",
  "schemaType": "WebApplication"
};

