'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { m, AnimatePresence } from 'framer-motion';
import { X, Trash2 } from 'lucide-react';
export function CdnOverlay({ isOpen, onClose, inputId, newCdn, setNewCdn, onAddCdn, cdns, onRemoveCdn, onAddPreset }) {
    return (_jsx(AnimatePresence, { children: isOpen && (_jsxs(m.div, { initial: { x: "100%" }, animate: { x: 0 }, exit: { x: "100%" }, className: "absolute inset-0 z-above bg-surface dark:bg-black/90 p-6 flex flex-col space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h3", { className: "text-sm font-black uppercase tracking-widest text-text", children: _jsx("label", { htmlFor: inputId, children: "External Libraries" }) }), _jsx("button", { onClick: onClose, className: "text-text-4 hover:text-blue", "aria-label": "Close libraries overlay", children: _jsx(X, { className: "w-5 h-5" }) })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex gap-2", children: [_jsx("input", { id: inputId, type: "text", placeholder: "CDN URL (CSS or JS)...", className: "flex-1 bg-bg border border-border rounded-xl px-4 py-2 text-xs outline-none focus:border-blue", value: newCdn, onChange: e => setNewCdn(e.target.value), onKeyDown: e => e.key === 'Enter' && onAddCdn() }), _jsx("button", { onClick: onAddCdn, className: "px-4 bg-blue text-white rounded-xl text-xs font-bold", "aria-label": "Add library", children: "Add" })] }), _jsxs("div", { className: "flex-1 overflow-y-auto space-y-2", children: [cdns.length === 0 && _jsx("p", { className: "text-xs text-text-4 text-center py-8", children: "No libraries added." }), cdns.map(url => (_jsxs("div", { className: "flex items-center justify-between p-3 bg-bg border border-border rounded-xl", children: [_jsx("span", { className: "text-xs font-mono truncate text-text-3 max-w-52", children: url }), _jsx("button", { onClick: () => onRemoveCdn(url), className: "text-text-4 hover:text-red-500 transition-colors", "aria-label": `Remove ${url}`, children: _jsx(Trash2, { className: "w-3.5 h-3.5" }) })] }, url)))] }), _jsxs("div", { className: "pt-4 border-t border-border", children: [_jsx("p", { className: "text-xs font-bold text-text-4 uppercase mb-2", children: "Common Presets" }), _jsx("div", { className: "flex flex-wrap gap-2", children: [
                                        { name: "Tailwind", url: "https://cdn.tailwindcss.com" },
                                        { name: "Bootstrap", url: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" },
                                        { name: "jQuery", url: "https://code.jquery.com/jquery-3.7.0.min.js" },
                                        { name: "React", url: "https://unpkg.com/react@18/umd/react.development.js" }
                                    ].map(lib => (_jsxs("button", { onClick: () => onAddPreset(lib.url), className: "px-3 py-1.5 rounded-lg bg-blue/5 border border-blue/10 text-xs font-bold text-blue hover:bg-blue hover:text-white transition-all", "aria-label": `Add ${lib.name} library`, children: ["+ ", lib.name] }, lib.name))) })] })] })] })) }));
}
