import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Legal Disclaimer | KaruviLab",
  description: "Important disclaimers regarding the use of KaruviLab's calculators, technical tools, and informational content.",
};

export default function LegalDisclaimer() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-16 space-y-8">
      <h1 className="text-4xl font-black tracking-tight text-text">Legal Disclaimer</h1>
      <p className="text-text-4 font-bold">Effective Date: May 30, 2026</p>

      <div className="p-6 bg-blue/10 border border-blue/20 rounded-2xl">
        <p className="text-lg font-black text-blue leading-relaxed">
          "KaruviLab provides tools and information for educational and informational purposes only. Results should not be considered financial, legal, tax, investment, medical, or professional advice."
        </p>
      </div>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">1. General Information Disclaimer</h2>
        <p>
          The information and utility tools provided on KaruviLab (https://karuvilab.com) are for general informational purposes only. 
          While we strive to keep the tools updated and correct, we make no representations or warranties of any kind, express or implied, 
          about the completeness, accuracy, reliability, suitability, or availability with respect to the website or the information, 
          products, services, or related graphics contained on the website for any purpose.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">2. No Professional Advice</h2>
        <p>
          The usage of KaruviLab does not create a professional-client relationship. You must not rely on the information provided 
          by our tools as an alternative to advice from a certified professional.
        </p>
        
        <h3 className="text-xl font-bold text-text mt-4">Financial & Investment Calculators</h3>
        <p>
          Tools such as the EMI Calculator, SIP Calculator, CAGR Calculator, and others are designed to provide illustrative estimates based on user input. 
          They do not account for hidden fees, changing market conditions, inflation, or specific institutional terms. 
          Always consult a licensed financial advisor before making investment or loan decisions.
        </p>

        <h3 className="text-xl font-bold text-text mt-4">Tax Calculators</h3>
        <p>
          Tax tools, including the GST Calculator, are based on standard mathematical formulas and general tax brackets. 
          Tax laws change frequently and vary by jurisdiction. You must consult a certified accountant or tax professional 
          before filing taxes or making pricing decisions based on our tool outputs.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">3. Technical Tool Disclaimer</h2>
        <p>
          Our developer utilities (e.g., Code Minifiers, HTML Viewers, Formatters) and file tools (e.g., PDF Splitter, Image Compressor) 
          are provided "as is." While they process data securely within your browser, KaruviLab is not responsible for any data corruption, 
          formatting loss, or unintended code execution resulting from the use of these utilities. Always maintain backups of your original files.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">4. Accuracy and Availability</h2>
        <p>
          Any reliance you place on the outputs generated by KaruviLab is strictly at your own risk. Every effort is made to keep the 
          website up and running smoothly. However, KaruviLab takes no responsibility for, and will not be liable for, the website 
          being temporarily unavailable due to technical issues beyond our control.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">5. Third-Party Content & External Links</h2>
        <p>
          Through this website, you are able to link to other websites which are not under the control of KaruviLab. 
          We have no control over the nature, content, and availability of those sites. The inclusion of any links does not 
          necessarily imply a recommendation or endorse the views expressed within them. Furthermore, user-generated content 
          previewed in our sandbox tools is not endorsed or vetted by KaruviLab.
        </p>
      </section>

      <section className="space-y-4 text-text-2 leading-relaxed">
        <h2 className="text-2xl font-black text-text">6. Contact</h2>
        <p>If you require clarification on any of our disclaimers, please contact us at:</p>
        <p><strong>Email:</strong> <a href="mailto:support@karuvilab.com" className="text-blue hover:underline">support@karuvilab.com</a></p>
      </section>
    </div>
  );
}