import { Metadata } from 'next';
import { CATEGORIES } from '@/src/tool-registry';
import { ToolShell } from '@/components/ui/ToolShell';
import { generateToolMetadata } from '@/src/lib/seo';
import { LearningHub, LearningSection } from "@/src/components/els/LearningHub";
import { QuizWidget } from "@/src/components/els/QuizWidget";
import SWPCalculatorClientWrapper from './SWPCalculatorClientWrapper';

const toolId = 'swp-calculator';
const cat = CATEGORIES.find(c => c.id === 'calculators');

export const metadata: Metadata = generateToolMetadata(toolId);

export default function Page() {
  return (
    <ToolShell 
      title="SWP Calculator"
      description="Plan your Systematic Withdrawal Plan (SWP) from your mutual fund investments."
      category={cat}
      toolId={toolId}
    >
      <SWPCalculatorClientWrapper />

      <LearningHub title="Understanding Systematic Withdrawal Plans">
        
        <LearningSection type="architecture" title="The Reverse SIP">
          <p>A Systematic Withdrawal Plan (SWP) is the exact opposite of an SIP. Instead of investing a fixed amount every month while you are working, you automatically withdraw a fixed amount every month from a lump sum corpus when you are retired.</p>
        </LearningSection>
        
        <LearningSection type="api" title="The Growth Engine">
          <p>The mathematical magic of an SWP is that the money you <em>haven't</em> withdrawn yet continues to grow in the market.</p>
          <p className="mt-2">If you have ₹1 Crore in a mutual fund generating 10% annually, and you withdraw ₹80,000 every month (which totals ₹9.6 Lakhs a year), your withdrawals are actually <strong>less</strong> than the interest being generated by the fund!</p>
          <p className="mt-2">In this scenario, your corpus will never deplete. In fact, it will keep growing, even while it pays you a monthly salary.</p>
        </LearningSection>

        <LearningSection type="performance" title="SWP vs. Fixed Deposit">
          <p>Many retirees prefer SWPs from mutual funds over standard Bank FDs for two major reasons:</p>
          <ul className="list-disc pl-5 mt-2 space-y-2">
            <li><strong>Higher Potential Returns:</strong> Equity or Hybrid mutual funds typically offer higher long-term returns than standard FDs, helping beat inflation.</li>
            <li><strong>Tax Efficiency:</strong> When you receive FD interest, the entire interest amount is fully taxable every year as regular income. When you withdraw money via an SWP, only the <em>capital gains</em> portion of that specific withdrawal is taxed. Furthermore, long-term capital gains on equity currently enjoy a ₹1.25 Lakh tax-free limit per year in India.</li>
          </ul>
        </LearningSection>

        <LearningSection type="general" title="Check Your Knowledge" fullWidth>
          <QuizWidget 
            questions={[
              {
                question: "How is an SWP fundamentally different from an FD?",
                options: [
                  "An SWP guarantees a specific interest rate, while an FD does not.",
                  "In an FD, the bank pays you interest while your principal remains locked. In an SWP, you are selling a small fraction of your mutual fund units every month.",
                  "An SWP is completely tax-free regardless of the amount.",
                  "An SWP requires a Demat account."
                ],
                correctIndex: 1,
                explanation: "An SWP works by automatically redeeming (selling) a specific number of mutual fund units each month to generate the cash you requested."
              },
              {
                question: "If your SWP withdrawal rate (e.g., 8% per year) is lower than the mutual fund's growth rate (e.g., 10% per year), what happens to your principal corpus?",
                options: [
                  "It depletes to zero in exactly 12.5 years.",
                  "It gets locked by the government.",
                  "It actually continues to grow larger, because it is generating returns faster than you are withdrawing cash.",
                  "It remains exactly the same."
                ],
                correctIndex: 2,
                explanation: "If growth outpaces withdrawals, the underlying corpus will compound infinitely."
              }
            ]}
          />
        </LearningSection>
      </LearningHub>
    </ToolShell>
  );
}
